/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AssistantMessageFeedbackClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantMessageFeedbackClientModel{}

// AssistantMessageFeedbackClientModel struct for AssistantMessageFeedbackClientModel
type AssistantMessageFeedbackClientModel struct {
	Rating  string         `json:"rating"`
	Content NullableString `json:"content,omitempty"`
	Tags    []string       `json:"tags,omitempty"`
}

type _AssistantMessageFeedbackClientModel AssistantMessageFeedbackClientModel

// NewAssistantMessageFeedbackClientModel instantiates a new AssistantMessageFeedbackClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantMessageFeedbackClientModel(rating string) *AssistantMessageFeedbackClientModel {
	this := AssistantMessageFeedbackClientModel{}
	this.Rating = rating
	return &this
}

// NewAssistantMessageFeedbackClientModelWithDefaults instantiates a new AssistantMessageFeedbackClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantMessageFeedbackClientModelWithDefaults() *AssistantMessageFeedbackClientModel {
	this := AssistantMessageFeedbackClientModel{}
	return &this
}

// GetRating returns the Rating field value
func (o *AssistantMessageFeedbackClientModel) GetRating() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rating
}

// GetRatingOk returns a tuple with the Rating field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageFeedbackClientModel) GetRatingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rating, true
}

// SetRating sets field value
func (o *AssistantMessageFeedbackClientModel) SetRating(v string) {
	o.Rating = v
}

// GetContent returns the Content field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageFeedbackClientModel) GetContent() string {
	if o == nil || IsNil(o.Content.Get()) {
		var ret string
		return ret
	}
	return *o.Content.Get()
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageFeedbackClientModel) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content.Get(), o.Content.IsSet()
}

// HasContent returns a boolean if a field has been set.
func (o *AssistantMessageFeedbackClientModel) HasContent() bool {
	if o != nil && o.Content.IsSet() {
		return true
	}

	return false
}

// SetContent gets a reference to the given NullableString and assigns it to the Content field.
func (o *AssistantMessageFeedbackClientModel) SetContent(v string) {
	o.Content.Set(&v)
}

// SetContentNil sets the value for Content to be an explicit nil
func (o *AssistantMessageFeedbackClientModel) SetContentNil() {
	o.Content.Set(nil)
}

// UnsetContent ensures that no value is present for Content, not even an explicit nil
func (o *AssistantMessageFeedbackClientModel) UnsetContent() {
	o.Content.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageFeedbackClientModel) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageFeedbackClientModel) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *AssistantMessageFeedbackClientModel) HasTags() bool {
	if o != nil && IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *AssistantMessageFeedbackClientModel) SetTags(v []string) {
	o.Tags = v
}

func (o AssistantMessageFeedbackClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantMessageFeedbackClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rating"] = o.Rating
	if o.Content.IsSet() {
		toSerialize["content"] = o.Content.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *AssistantMessageFeedbackClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rating",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssistantMessageFeedbackClientModel := _AssistantMessageFeedbackClientModel{}

	err = json.Unmarshal(bytes, &varAssistantMessageFeedbackClientModel)

	if err != nil {
		return err
	}

	*o = AssistantMessageFeedbackClientModel(varAssistantMessageFeedbackClientModel)

	return err
}

type NullableAssistantMessageFeedbackClientModel struct {
	value *AssistantMessageFeedbackClientModel
	isSet bool
}

func (v NullableAssistantMessageFeedbackClientModel) Get() *AssistantMessageFeedbackClientModel {
	return v.value
}

func (v *NullableAssistantMessageFeedbackClientModel) Set(val *AssistantMessageFeedbackClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantMessageFeedbackClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantMessageFeedbackClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantMessageFeedbackClientModel(val *AssistantMessageFeedbackClientModel) *NullableAssistantMessageFeedbackClientModel {
	return &NullableAssistantMessageFeedbackClientModel{value: val, isSet: true}
}

func (v NullableAssistantMessageFeedbackClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantMessageFeedbackClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
