/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedClientResponseModelFilterOptionClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedClientResponseModelFilterOptionClientModel{}

// PaginatedClientResponseModelFilterOptionClientModel struct for PaginatedClientResponseModelFilterOptionClientModel
type PaginatedClientResponseModelFilterOptionClientModel struct {
	Data       []FilterOptionClientModel `json:"data"`
	Pagination PaginationClientInfoModel `json:"pagination"`
}

type _PaginatedClientResponseModelFilterOptionClientModel PaginatedClientResponseModelFilterOptionClientModel

// NewPaginatedClientResponseModelFilterOptionClientModel instantiates a new PaginatedClientResponseModelFilterOptionClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedClientResponseModelFilterOptionClientModel(data []FilterOptionClientModel, pagination PaginationClientInfoModel) *PaginatedClientResponseModelFilterOptionClientModel {
	this := PaginatedClientResponseModelFilterOptionClientModel{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewPaginatedClientResponseModelFilterOptionClientModelWithDefaults instantiates a new PaginatedClientResponseModelFilterOptionClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedClientResponseModelFilterOptionClientModelWithDefaults() *PaginatedClientResponseModelFilterOptionClientModel {
	this := PaginatedClientResponseModelFilterOptionClientModel{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedClientResponseModelFilterOptionClientModel) GetData() []FilterOptionClientModel {
	if o == nil {
		var ret []FilterOptionClientModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedClientResponseModelFilterOptionClientModel) GetDataOk() ([]FilterOptionClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedClientResponseModelFilterOptionClientModel) SetData(v []FilterOptionClientModel) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *PaginatedClientResponseModelFilterOptionClientModel) GetPagination() PaginationClientInfoModel {
	if o == nil {
		var ret PaginationClientInfoModel
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedClientResponseModelFilterOptionClientModel) GetPaginationOk() (*PaginationClientInfoModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedClientResponseModelFilterOptionClientModel) SetPagination(v PaginationClientInfoModel) {
	o.Pagination = v
}

func (o PaginatedClientResponseModelFilterOptionClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedClientResponseModelFilterOptionClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *PaginatedClientResponseModelFilterOptionClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedClientResponseModelFilterOptionClientModel := _PaginatedClientResponseModelFilterOptionClientModel{}

	err = json.Unmarshal(bytes, &varPaginatedClientResponseModelFilterOptionClientModel)

	if err != nil {
		return err
	}

	*o = PaginatedClientResponseModelFilterOptionClientModel(varPaginatedClientResponseModelFilterOptionClientModel)

	return err
}

type NullablePaginatedClientResponseModelFilterOptionClientModel struct {
	value *PaginatedClientResponseModelFilterOptionClientModel
	isSet bool
}

func (v NullablePaginatedClientResponseModelFilterOptionClientModel) Get() *PaginatedClientResponseModelFilterOptionClientModel {
	return v.value
}

func (v *NullablePaginatedClientResponseModelFilterOptionClientModel) Set(val *PaginatedClientResponseModelFilterOptionClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedClientResponseModelFilterOptionClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedClientResponseModelFilterOptionClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedClientResponseModelFilterOptionClientModel(val *PaginatedClientResponseModelFilterOptionClientModel) *NullablePaginatedClientResponseModelFilterOptionClientModel {
	return &NullablePaginatedClientResponseModelFilterOptionClientModel{value: val, isSet: true}
}

func (v NullablePaginatedClientResponseModelFilterOptionClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedClientResponseModelFilterOptionClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
