/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AssistantMessageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantMessageRequest{}

// AssistantMessageRequest struct for AssistantMessageRequest
type AssistantMessageRequest struct {
	Message        string         `json:"message"`
	SystemPromptId NullableString `json:"system_prompt_id,omitempty"`
	ConversationId NullableString `json:"conversation_id,omitempty"`
}

type _AssistantMessageRequest AssistantMessageRequest

// NewAssistantMessageRequest instantiates a new AssistantMessageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantMessageRequest(message string) *AssistantMessageRequest {
	this := AssistantMessageRequest{}
	this.Message = message
	return &this
}

// NewAssistantMessageRequestWithDefaults instantiates a new AssistantMessageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantMessageRequestWithDefaults() *AssistantMessageRequest {
	this := AssistantMessageRequest{}
	return &this
}

// GetMessage returns the Message field value
func (o *AssistantMessageRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AssistantMessageRequest) SetMessage(v string) {
	o.Message = v
}

// GetSystemPromptId returns the SystemPromptId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageRequest) GetSystemPromptId() string {
	if o == nil || IsNil(o.SystemPromptId.Get()) {
		var ret string
		return ret
	}
	return *o.SystemPromptId.Get()
}

// GetSystemPromptIdOk returns a tuple with the SystemPromptId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageRequest) GetSystemPromptIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SystemPromptId.Get(), o.SystemPromptId.IsSet()
}

// HasSystemPromptId returns a boolean if a field has been set.
func (o *AssistantMessageRequest) HasSystemPromptId() bool {
	if o != nil && o.SystemPromptId.IsSet() {
		return true
	}

	return false
}

// SetSystemPromptId gets a reference to the given NullableString and assigns it to the SystemPromptId field.
func (o *AssistantMessageRequest) SetSystemPromptId(v string) {
	o.SystemPromptId.Set(&v)
}

// SetSystemPromptIdNil sets the value for SystemPromptId to be an explicit nil
func (o *AssistantMessageRequest) SetSystemPromptIdNil() {
	o.SystemPromptId.Set(nil)
}

// UnsetSystemPromptId ensures that no value is present for SystemPromptId, not even an explicit nil
func (o *AssistantMessageRequest) UnsetSystemPromptId() {
	o.SystemPromptId.Unset()
}

// GetConversationId returns the ConversationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageRequest) GetConversationId() string {
	if o == nil || IsNil(o.ConversationId.Get()) {
		var ret string
		return ret
	}
	return *o.ConversationId.Get()
}

// GetConversationIdOk returns a tuple with the ConversationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageRequest) GetConversationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConversationId.Get(), o.ConversationId.IsSet()
}

// HasConversationId returns a boolean if a field has been set.
func (o *AssistantMessageRequest) HasConversationId() bool {
	if o != nil && o.ConversationId.IsSet() {
		return true
	}

	return false
}

// SetConversationId gets a reference to the given NullableString and assigns it to the ConversationId field.
func (o *AssistantMessageRequest) SetConversationId(v string) {
	o.ConversationId.Set(&v)
}

// SetConversationIdNil sets the value for ConversationId to be an explicit nil
func (o *AssistantMessageRequest) SetConversationIdNil() {
	o.ConversationId.Set(nil)
}

// UnsetConversationId ensures that no value is present for ConversationId, not even an explicit nil
func (o *AssistantMessageRequest) UnsetConversationId() {
	o.ConversationId.Unset()
}

func (o AssistantMessageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantMessageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if o.SystemPromptId.IsSet() {
		toSerialize["system_prompt_id"] = o.SystemPromptId.Get()
	}
	if o.ConversationId.IsSet() {
		toSerialize["conversation_id"] = o.ConversationId.Get()
	}
	return toSerialize, nil
}

func (o *AssistantMessageRequest) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssistantMessageRequest := _AssistantMessageRequest{}

	err = json.Unmarshal(bytes, &varAssistantMessageRequest)

	if err != nil {
		return err
	}

	*o = AssistantMessageRequest(varAssistantMessageRequest)

	return err
}

type NullableAssistantMessageRequest struct {
	value *AssistantMessageRequest
	isSet bool
}

func (v NullableAssistantMessageRequest) Get() *AssistantMessageRequest {
	return v.value
}

func (v *NullableAssistantMessageRequest) Set(val *AssistantMessageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantMessageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantMessageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantMessageRequest(val *AssistantMessageRequest) *NullableAssistantMessageRequest {
	return &NullableAssistantMessageRequest{value: val, isSet: true}
}

func (v NullableAssistantMessageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantMessageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
