/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MessageDataRequestCTAClientModelRequestAgain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageDataRequestCTAClientModelRequestAgain{}

// MessageDataRequestCTAClientModelRequestAgain struct for MessageDataRequestCTAClientModelRequestAgain
type MessageDataRequestCTAClientModelRequestAgain struct {
	Entitlements     []AccessRequestClientModel `json:"entitlements"`
	Justification    string                     `json:"justification"`
	RequiresApproval bool                       `json:"requires_approval"`
	ValidRequest     bool                       `json:"valid_request"`
}

type _MessageDataRequestCTAClientModelRequestAgain MessageDataRequestCTAClientModelRequestAgain

// NewMessageDataRequestCTAClientModelRequestAgain instantiates a new MessageDataRequestCTAClientModelRequestAgain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageDataRequestCTAClientModelRequestAgain(entitlements []AccessRequestClientModel, justification string, requiresApproval bool, validRequest bool) *MessageDataRequestCTAClientModelRequestAgain {
	this := MessageDataRequestCTAClientModelRequestAgain{}
	this.Entitlements = entitlements
	this.Justification = justification
	this.RequiresApproval = requiresApproval
	this.ValidRequest = validRequest
	return &this
}

// NewMessageDataRequestCTAClientModelRequestAgainWithDefaults instantiates a new MessageDataRequestCTAClientModelRequestAgain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageDataRequestCTAClientModelRequestAgainWithDefaults() *MessageDataRequestCTAClientModelRequestAgain {
	this := MessageDataRequestCTAClientModelRequestAgain{}
	return &this
}

// GetEntitlements returns the Entitlements field value
func (o *MessageDataRequestCTAClientModelRequestAgain) GetEntitlements() []AccessRequestClientModel {
	if o == nil {
		var ret []AccessRequestClientModel
		return ret
	}

	return o.Entitlements
}

// GetEntitlementsOk returns a tuple with the Entitlements field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestCTAClientModelRequestAgain) GetEntitlementsOk() ([]AccessRequestClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entitlements, true
}

// SetEntitlements sets field value
func (o *MessageDataRequestCTAClientModelRequestAgain) SetEntitlements(v []AccessRequestClientModel) {
	o.Entitlements = v
}

// GetJustification returns the Justification field value
func (o *MessageDataRequestCTAClientModelRequestAgain) GetJustification() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Justification
}

// GetJustificationOk returns a tuple with the Justification field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestCTAClientModelRequestAgain) GetJustificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Justification, true
}

// SetJustification sets field value
func (o *MessageDataRequestCTAClientModelRequestAgain) SetJustification(v string) {
	o.Justification = v
}

// GetRequiresApproval returns the RequiresApproval field value
func (o *MessageDataRequestCTAClientModelRequestAgain) GetRequiresApproval() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresApproval
}

// GetRequiresApprovalOk returns a tuple with the RequiresApproval field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestCTAClientModelRequestAgain) GetRequiresApprovalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresApproval, true
}

// SetRequiresApproval sets field value
func (o *MessageDataRequestCTAClientModelRequestAgain) SetRequiresApproval(v bool) {
	o.RequiresApproval = v
}

// GetValidRequest returns the ValidRequest field value
func (o *MessageDataRequestCTAClientModelRequestAgain) GetValidRequest() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ValidRequest
}

// GetValidRequestOk returns a tuple with the ValidRequest field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestCTAClientModelRequestAgain) GetValidRequestOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidRequest, true
}

// SetValidRequest sets field value
func (o *MessageDataRequestCTAClientModelRequestAgain) SetValidRequest(v bool) {
	o.ValidRequest = v
}

func (o MessageDataRequestCTAClientModelRequestAgain) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageDataRequestCTAClientModelRequestAgain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entitlements"] = o.Entitlements
	toSerialize["justification"] = o.Justification
	toSerialize["requires_approval"] = o.RequiresApproval
	toSerialize["valid_request"] = o.ValidRequest
	return toSerialize, nil
}

func (o *MessageDataRequestCTAClientModelRequestAgain) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entitlements",
		"justification",
		"requires_approval",
		"valid_request",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageDataRequestCTAClientModelRequestAgain := _MessageDataRequestCTAClientModelRequestAgain{}

	err = json.Unmarshal(bytes, &varMessageDataRequestCTAClientModelRequestAgain)

	if err != nil {
		return err
	}

	*o = MessageDataRequestCTAClientModelRequestAgain(varMessageDataRequestCTAClientModelRequestAgain)

	return err
}

type NullableMessageDataRequestCTAClientModelRequestAgain struct {
	value *MessageDataRequestCTAClientModelRequestAgain
	isSet bool
}

func (v NullableMessageDataRequestCTAClientModelRequestAgain) Get() *MessageDataRequestCTAClientModelRequestAgain {
	return v.value
}

func (v *NullableMessageDataRequestCTAClientModelRequestAgain) Set(val *MessageDataRequestCTAClientModelRequestAgain) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageDataRequestCTAClientModelRequestAgain) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageDataRequestCTAClientModelRequestAgain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageDataRequestCTAClientModelRequestAgain(val *MessageDataRequestCTAClientModelRequestAgain) *NullableMessageDataRequestCTAClientModelRequestAgain {
	return &NullableMessageDataRequestCTAClientModelRequestAgain{value: val, isSet: true}
}

func (v NullableMessageDataRequestCTAClientModelRequestAgain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageDataRequestCTAClientModelRequestAgain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
