/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the LauncherClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LauncherClientModel{}

// LauncherClientModel struct for LauncherClientModel
type LauncherClientModel struct {
	Id                string         `json:"id"`
	DisplayName       string         `json:"display_name"`
	LauncherType      string         `json:"launcher_type"`
	AuthCommand       NullableString `json:"auth_command,omitempty"`
	InvocationCommand string         `json:"invocation_command"`
}

type _LauncherClientModel LauncherClientModel

// NewLauncherClientModel instantiates a new LauncherClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLauncherClientModel(id string, displayName string, launcherType string, invocationCommand string) *LauncherClientModel {
	this := LauncherClientModel{}
	this.Id = id
	this.DisplayName = displayName
	this.LauncherType = launcherType
	this.InvocationCommand = invocationCommand
	return &this
}

// NewLauncherClientModelWithDefaults instantiates a new LauncherClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLauncherClientModelWithDefaults() *LauncherClientModel {
	this := LauncherClientModel{}
	return &this
}

// GetId returns the Id field value
func (o *LauncherClientModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LauncherClientModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LauncherClientModel) SetId(v string) {
	o.Id = v
}

// GetDisplayName returns the DisplayName field value
func (o *LauncherClientModel) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *LauncherClientModel) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *LauncherClientModel) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetLauncherType returns the LauncherType field value
func (o *LauncherClientModel) GetLauncherType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LauncherType
}

// GetLauncherTypeOk returns a tuple with the LauncherType field value
// and a boolean to check if the value has been set.
func (o *LauncherClientModel) GetLauncherTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LauncherType, true
}

// SetLauncherType sets field value
func (o *LauncherClientModel) SetLauncherType(v string) {
	o.LauncherType = v
}

// GetAuthCommand returns the AuthCommand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LauncherClientModel) GetAuthCommand() string {
	if o == nil || IsNil(o.AuthCommand.Get()) {
		var ret string
		return ret
	}
	return *o.AuthCommand.Get()
}

// GetAuthCommandOk returns a tuple with the AuthCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LauncherClientModel) GetAuthCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthCommand.Get(), o.AuthCommand.IsSet()
}

// HasAuthCommand returns a boolean if a field has been set.
func (o *LauncherClientModel) HasAuthCommand() bool {
	if o != nil && o.AuthCommand.IsSet() {
		return true
	}

	return false
}

// SetAuthCommand gets a reference to the given NullableString and assigns it to the AuthCommand field.
func (o *LauncherClientModel) SetAuthCommand(v string) {
	o.AuthCommand.Set(&v)
}

// SetAuthCommandNil sets the value for AuthCommand to be an explicit nil
func (o *LauncherClientModel) SetAuthCommandNil() {
	o.AuthCommand.Set(nil)
}

// UnsetAuthCommand ensures that no value is present for AuthCommand, not even an explicit nil
func (o *LauncherClientModel) UnsetAuthCommand() {
	o.AuthCommand.Unset()
}

// GetInvocationCommand returns the InvocationCommand field value
func (o *LauncherClientModel) GetInvocationCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvocationCommand
}

// GetInvocationCommandOk returns a tuple with the InvocationCommand field value
// and a boolean to check if the value has been set.
func (o *LauncherClientModel) GetInvocationCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvocationCommand, true
}

// SetInvocationCommand sets field value
func (o *LauncherClientModel) SetInvocationCommand(v string) {
	o.InvocationCommand = v
}

func (o LauncherClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LauncherClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["display_name"] = o.DisplayName
	toSerialize["launcher_type"] = o.LauncherType
	if o.AuthCommand.IsSet() {
		toSerialize["auth_command"] = o.AuthCommand.Get()
	}
	toSerialize["invocation_command"] = o.InvocationCommand
	return toSerialize, nil
}

func (o *LauncherClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"display_name",
		"launcher_type",
		"invocation_command",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLauncherClientModel := _LauncherClientModel{}

	err = json.Unmarshal(bytes, &varLauncherClientModel)

	if err != nil {
		return err
	}

	*o = LauncherClientModel(varLauncherClientModel)

	return err
}

type NullableLauncherClientModel struct {
	value *LauncherClientModel
	isSet bool
}

func (v NullableLauncherClientModel) Get() *LauncherClientModel {
	return v.value
}

func (v *NullableLauncherClientModel) Set(val *LauncherClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableLauncherClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableLauncherClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLauncherClientModel(val *LauncherClientModel) *NullableLauncherClientModel {
	return &NullableLauncherClientModel{value: val, isSet: true}
}

func (v NullableLauncherClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLauncherClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
