/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SessionEventClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionEventClientModel{}

// SessionEventClientModel struct for SessionEventClientModel
type SessionEventClientModel struct {
	Type           string                                        `json:"type"`
	EventStartTime float64                                       `json:"event_start_time"`
	EventEndTime   NullableFloat64                               `json:"event_end_time,omitempty"`
	ToolActivity   NullableSessionEventClientModelToolActivity   `json:"tool_activity,omitempty"`
	AccessElevated NullableSessionEventClientModelAccessElevated `json:"access_elevated,omitempty"`
}

type _SessionEventClientModel SessionEventClientModel

// NewSessionEventClientModel instantiates a new SessionEventClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionEventClientModel(type_ string, eventStartTime float64) *SessionEventClientModel {
	this := SessionEventClientModel{}
	this.Type = type_
	this.EventStartTime = eventStartTime
	return &this
}

// NewSessionEventClientModelWithDefaults instantiates a new SessionEventClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionEventClientModelWithDefaults() *SessionEventClientModel {
	this := SessionEventClientModel{}
	return &this
}

// GetType returns the Type field value
func (o *SessionEventClientModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SessionEventClientModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SessionEventClientModel) SetType(v string) {
	o.Type = v
}

// GetEventStartTime returns the EventStartTime field value
func (o *SessionEventClientModel) GetEventStartTime() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.EventStartTime
}

// GetEventStartTimeOk returns a tuple with the EventStartTime field value
// and a boolean to check if the value has been set.
func (o *SessionEventClientModel) GetEventStartTimeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventStartTime, true
}

// SetEventStartTime sets field value
func (o *SessionEventClientModel) SetEventStartTime(v float64) {
	o.EventStartTime = v
}

// GetEventEndTime returns the EventEndTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionEventClientModel) GetEventEndTime() float64 {
	if o == nil || IsNil(o.EventEndTime.Get()) {
		var ret float64
		return ret
	}
	return *o.EventEndTime.Get()
}

// GetEventEndTimeOk returns a tuple with the EventEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionEventClientModel) GetEventEndTimeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventEndTime.Get(), o.EventEndTime.IsSet()
}

// HasEventEndTime returns a boolean if a field has been set.
func (o *SessionEventClientModel) HasEventEndTime() bool {
	if o != nil && o.EventEndTime.IsSet() {
		return true
	}

	return false
}

// SetEventEndTime gets a reference to the given NullableFloat64 and assigns it to the EventEndTime field.
func (o *SessionEventClientModel) SetEventEndTime(v float64) {
	o.EventEndTime.Set(&v)
}

// SetEventEndTimeNil sets the value for EventEndTime to be an explicit nil
func (o *SessionEventClientModel) SetEventEndTimeNil() {
	o.EventEndTime.Set(nil)
}

// UnsetEventEndTime ensures that no value is present for EventEndTime, not even an explicit nil
func (o *SessionEventClientModel) UnsetEventEndTime() {
	o.EventEndTime.Unset()
}

// GetToolActivity returns the ToolActivity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionEventClientModel) GetToolActivity() SessionEventClientModelToolActivity {
	if o == nil || IsNil(o.ToolActivity.Get()) {
		var ret SessionEventClientModelToolActivity
		return ret
	}
	return *o.ToolActivity.Get()
}

// GetToolActivityOk returns a tuple with the ToolActivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionEventClientModel) GetToolActivityOk() (*SessionEventClientModelToolActivity, bool) {
	if o == nil {
		return nil, false
	}
	return o.ToolActivity.Get(), o.ToolActivity.IsSet()
}

// HasToolActivity returns a boolean if a field has been set.
func (o *SessionEventClientModel) HasToolActivity() bool {
	if o != nil && o.ToolActivity.IsSet() {
		return true
	}

	return false
}

// SetToolActivity gets a reference to the given NullableSessionEventClientModelToolActivity and assigns it to the ToolActivity field.
func (o *SessionEventClientModel) SetToolActivity(v SessionEventClientModelToolActivity) {
	o.ToolActivity.Set(&v)
}

// SetToolActivityNil sets the value for ToolActivity to be an explicit nil
func (o *SessionEventClientModel) SetToolActivityNil() {
	o.ToolActivity.Set(nil)
}

// UnsetToolActivity ensures that no value is present for ToolActivity, not even an explicit nil
func (o *SessionEventClientModel) UnsetToolActivity() {
	o.ToolActivity.Unset()
}

// GetAccessElevated returns the AccessElevated field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionEventClientModel) GetAccessElevated() SessionEventClientModelAccessElevated {
	if o == nil || IsNil(o.AccessElevated.Get()) {
		var ret SessionEventClientModelAccessElevated
		return ret
	}
	return *o.AccessElevated.Get()
}

// GetAccessElevatedOk returns a tuple with the AccessElevated field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionEventClientModel) GetAccessElevatedOk() (*SessionEventClientModelAccessElevated, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccessElevated.Get(), o.AccessElevated.IsSet()
}

// HasAccessElevated returns a boolean if a field has been set.
func (o *SessionEventClientModel) HasAccessElevated() bool {
	if o != nil && o.AccessElevated.IsSet() {
		return true
	}

	return false
}

// SetAccessElevated gets a reference to the given NullableSessionEventClientModelAccessElevated and assigns it to the AccessElevated field.
func (o *SessionEventClientModel) SetAccessElevated(v SessionEventClientModelAccessElevated) {
	o.AccessElevated.Set(&v)
}

// SetAccessElevatedNil sets the value for AccessElevated to be an explicit nil
func (o *SessionEventClientModel) SetAccessElevatedNil() {
	o.AccessElevated.Set(nil)
}

// UnsetAccessElevated ensures that no value is present for AccessElevated, not even an explicit nil
func (o *SessionEventClientModel) UnsetAccessElevated() {
	o.AccessElevated.Unset()
}

func (o SessionEventClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionEventClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["event_start_time"] = o.EventStartTime
	if o.EventEndTime.IsSet() {
		toSerialize["event_end_time"] = o.EventEndTime.Get()
	}
	if o.ToolActivity.IsSet() {
		toSerialize["tool_activity"] = o.ToolActivity.Get()
	}
	if o.AccessElevated.IsSet() {
		toSerialize["access_elevated"] = o.AccessElevated.Get()
	}
	return toSerialize, nil
}

func (o *SessionEventClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"event_start_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionEventClientModel := _SessionEventClientModel{}

	err = json.Unmarshal(bytes, &varSessionEventClientModel)

	if err != nil {
		return err
	}

	*o = SessionEventClientModel(varSessionEventClientModel)

	return err
}

type NullableSessionEventClientModel struct {
	value *SessionEventClientModel
	isSet bool
}

func (v NullableSessionEventClientModel) Get() *SessionEventClientModel {
	return v.value
}

func (v *NullableSessionEventClientModel) Set(val *SessionEventClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionEventClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionEventClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionEventClientModel(val *SessionEventClientModel) *NullableSessionEventClientModel {
	return &NullableSessionEventClientModel{value: val, isSet: true}
}

func (v NullableSessionEventClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionEventClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
