/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedClientResponseModelAssistantMessageClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedClientResponseModelAssistantMessageClientModel{}

// PaginatedClientResponseModelAssistantMessageClientModel struct for PaginatedClientResponseModelAssistantMessageClientModel
type PaginatedClientResponseModelAssistantMessageClientModel struct {
	Data       []AssistantMessageClientModel `json:"data"`
	Pagination PaginationClientInfoModel     `json:"pagination"`
}

type _PaginatedClientResponseModelAssistantMessageClientModel PaginatedClientResponseModelAssistantMessageClientModel

// NewPaginatedClientResponseModelAssistantMessageClientModel instantiates a new PaginatedClientResponseModelAssistantMessageClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedClientResponseModelAssistantMessageClientModel(data []AssistantMessageClientModel, pagination PaginationClientInfoModel) *PaginatedClientResponseModelAssistantMessageClientModel {
	this := PaginatedClientResponseModelAssistantMessageClientModel{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewPaginatedClientResponseModelAssistantMessageClientModelWithDefaults instantiates a new PaginatedClientResponseModelAssistantMessageClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedClientResponseModelAssistantMessageClientModelWithDefaults() *PaginatedClientResponseModelAssistantMessageClientModel {
	this := PaginatedClientResponseModelAssistantMessageClientModel{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedClientResponseModelAssistantMessageClientModel) GetData() []AssistantMessageClientModel {
	if o == nil {
		var ret []AssistantMessageClientModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedClientResponseModelAssistantMessageClientModel) GetDataOk() ([]AssistantMessageClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedClientResponseModelAssistantMessageClientModel) SetData(v []AssistantMessageClientModel) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *PaginatedClientResponseModelAssistantMessageClientModel) GetPagination() PaginationClientInfoModel {
	if o == nil {
		var ret PaginationClientInfoModel
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedClientResponseModelAssistantMessageClientModel) GetPaginationOk() (*PaginationClientInfoModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedClientResponseModelAssistantMessageClientModel) SetPagination(v PaginationClientInfoModel) {
	o.Pagination = v
}

func (o PaginatedClientResponseModelAssistantMessageClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedClientResponseModelAssistantMessageClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *PaginatedClientResponseModelAssistantMessageClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedClientResponseModelAssistantMessageClientModel := _PaginatedClientResponseModelAssistantMessageClientModel{}

	err = json.Unmarshal(bytes, &varPaginatedClientResponseModelAssistantMessageClientModel)

	if err != nil {
		return err
	}

	*o = PaginatedClientResponseModelAssistantMessageClientModel(varPaginatedClientResponseModelAssistantMessageClientModel)

	return err
}

type NullablePaginatedClientResponseModelAssistantMessageClientModel struct {
	value *PaginatedClientResponseModelAssistantMessageClientModel
	isSet bool
}

func (v NullablePaginatedClientResponseModelAssistantMessageClientModel) Get() *PaginatedClientResponseModelAssistantMessageClientModel {
	return v.value
}

func (v *NullablePaginatedClientResponseModelAssistantMessageClientModel) Set(val *PaginatedClientResponseModelAssistantMessageClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedClientResponseModelAssistantMessageClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedClientResponseModelAssistantMessageClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedClientResponseModelAssistantMessageClientModel(val *PaginatedClientResponseModelAssistantMessageClientModel) *NullablePaginatedClientResponseModelAssistantMessageClientModel {
	return &NullablePaginatedClientResponseModelAssistantMessageClientModel{value: val, isSet: true}
}

func (v NullablePaginatedClientResponseModelAssistantMessageClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedClientResponseModelAssistantMessageClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
