/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResponseResolvedTrustPolicyClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseResolvedTrustPolicyClientModel{}

// PaginatedResponseResolvedTrustPolicyClientModel struct for PaginatedResponseResolvedTrustPolicyClientModel
type PaginatedResponseResolvedTrustPolicyClientModel struct {
	Data       []ResolvedTrustPolicyClientModel `json:"data"`
	Pagination PaginationInfo                   `json:"pagination"`
}

type _PaginatedResponseResolvedTrustPolicyClientModel PaginatedResponseResolvedTrustPolicyClientModel

// NewPaginatedResponseResolvedTrustPolicyClientModel instantiates a new PaginatedResponseResolvedTrustPolicyClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseResolvedTrustPolicyClientModel(data []ResolvedTrustPolicyClientModel, pagination PaginationInfo) *PaginatedResponseResolvedTrustPolicyClientModel {
	this := PaginatedResponseResolvedTrustPolicyClientModel{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewPaginatedResponseResolvedTrustPolicyClientModelWithDefaults instantiates a new PaginatedResponseResolvedTrustPolicyClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseResolvedTrustPolicyClientModelWithDefaults() *PaginatedResponseResolvedTrustPolicyClientModel {
	this := PaginatedResponseResolvedTrustPolicyClientModel{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedResponseResolvedTrustPolicyClientModel) GetData() []ResolvedTrustPolicyClientModel {
	if o == nil {
		var ret []ResolvedTrustPolicyClientModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseResolvedTrustPolicyClientModel) GetDataOk() ([]ResolvedTrustPolicyClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedResponseResolvedTrustPolicyClientModel) SetData(v []ResolvedTrustPolicyClientModel) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *PaginatedResponseResolvedTrustPolicyClientModel) GetPagination() PaginationInfo {
	if o == nil {
		var ret PaginationInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseResolvedTrustPolicyClientModel) GetPaginationOk() (*PaginationInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedResponseResolvedTrustPolicyClientModel) SetPagination(v PaginationInfo) {
	o.Pagination = v
}

func (o PaginatedResponseResolvedTrustPolicyClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseResolvedTrustPolicyClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *PaginatedResponseResolvedTrustPolicyClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseResolvedTrustPolicyClientModel := _PaginatedResponseResolvedTrustPolicyClientModel{}

	err = json.Unmarshal(bytes, &varPaginatedResponseResolvedTrustPolicyClientModel)

	if err != nil {
		return err
	}

	*o = PaginatedResponseResolvedTrustPolicyClientModel(varPaginatedResponseResolvedTrustPolicyClientModel)

	return err
}

type NullablePaginatedResponseResolvedTrustPolicyClientModel struct {
	value *PaginatedResponseResolvedTrustPolicyClientModel
	isSet bool
}

func (v NullablePaginatedResponseResolvedTrustPolicyClientModel) Get() *PaginatedResponseResolvedTrustPolicyClientModel {
	return v.value
}

func (v *NullablePaginatedResponseResolvedTrustPolicyClientModel) Set(val *PaginatedResponseResolvedTrustPolicyClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseResolvedTrustPolicyClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseResolvedTrustPolicyClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseResolvedTrustPolicyClientModel(val *PaginatedResponseResolvedTrustPolicyClientModel) *NullablePaginatedResponseResolvedTrustPolicyClientModel {
	return &NullablePaginatedResponseResolvedTrustPolicyClientModel{value: val, isSet: true}
}

func (v NullablePaginatedResponseResolvedTrustPolicyClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseResolvedTrustPolicyClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
