/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AssistantConversationSuggestionClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantConversationSuggestionClientModel{}

// AssistantConversationSuggestionClientModel struct for AssistantConversationSuggestionClientModel
type AssistantConversationSuggestionClientModel struct {
	Id      string `json:"id"`
	Title   string `json:"title"`
	Type    string `json:"type"`
	Content string `json:"content"`
}

type _AssistantConversationSuggestionClientModel AssistantConversationSuggestionClientModel

// NewAssistantConversationSuggestionClientModel instantiates a new AssistantConversationSuggestionClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantConversationSuggestionClientModel(id string, title string, type_ string, content string) *AssistantConversationSuggestionClientModel {
	this := AssistantConversationSuggestionClientModel{}
	this.Id = id
	this.Title = title
	this.Type = type_
	this.Content = content
	return &this
}

// NewAssistantConversationSuggestionClientModelWithDefaults instantiates a new AssistantConversationSuggestionClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantConversationSuggestionClientModelWithDefaults() *AssistantConversationSuggestionClientModel {
	this := AssistantConversationSuggestionClientModel{}
	return &this
}

// GetId returns the Id field value
func (o *AssistantConversationSuggestionClientModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AssistantConversationSuggestionClientModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AssistantConversationSuggestionClientModel) SetId(v string) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *AssistantConversationSuggestionClientModel) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *AssistantConversationSuggestionClientModel) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *AssistantConversationSuggestionClientModel) SetTitle(v string) {
	o.Title = v
}

// GetType returns the Type field value
func (o *AssistantConversationSuggestionClientModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AssistantConversationSuggestionClientModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AssistantConversationSuggestionClientModel) SetType(v string) {
	o.Type = v
}

// GetContent returns the Content field value
func (o *AssistantConversationSuggestionClientModel) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *AssistantConversationSuggestionClientModel) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *AssistantConversationSuggestionClientModel) SetContent(v string) {
	o.Content = v
}

func (o AssistantConversationSuggestionClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantConversationSuggestionClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	toSerialize["type"] = o.Type
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *AssistantConversationSuggestionClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"title",
		"type",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssistantConversationSuggestionClientModel := _AssistantConversationSuggestionClientModel{}

	err = json.Unmarshal(bytes, &varAssistantConversationSuggestionClientModel)

	if err != nil {
		return err
	}

	*o = AssistantConversationSuggestionClientModel(varAssistantConversationSuggestionClientModel)

	return err
}

type NullableAssistantConversationSuggestionClientModel struct {
	value *AssistantConversationSuggestionClientModel
	isSet bool
}

func (v NullableAssistantConversationSuggestionClientModel) Get() *AssistantConversationSuggestionClientModel {
	return v.value
}

func (v *NullableAssistantConversationSuggestionClientModel) Set(val *AssistantConversationSuggestionClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantConversationSuggestionClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantConversationSuggestionClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantConversationSuggestionClientModel(val *AssistantConversationSuggestionClientModel) *NullableAssistantConversationSuggestionClientModel {
	return &NullableAssistantConversationSuggestionClientModel{value: val, isSet: true}
}

func (v NullableAssistantConversationSuggestionClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantConversationSuggestionClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
