/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RequestCustomFieldModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestCustomFieldModel{}

// RequestCustomFieldModel struct for RequestCustomFieldModel
type RequestCustomFieldModel struct {
	Id          string                         `json:"id"`
	Type        string                         `json:"type"`
	Label       string                         `json:"label"`
	Placeholder string                         `json:"placeholder"`
	Values      []RequestCustomFieldValueModel `json:"values"`
	Default     NullableString                 `json:"default,omitempty"`
	Required    bool                           `json:"required"`
}

type _RequestCustomFieldModel RequestCustomFieldModel

// NewRequestCustomFieldModel instantiates a new RequestCustomFieldModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestCustomFieldModel(id string, type_ string, label string, placeholder string, values []RequestCustomFieldValueModel, required bool) *RequestCustomFieldModel {
	this := RequestCustomFieldModel{}
	this.Id = id
	this.Type = type_
	this.Label = label
	this.Placeholder = placeholder
	this.Values = values
	this.Required = required
	return &this
}

// NewRequestCustomFieldModelWithDefaults instantiates a new RequestCustomFieldModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestCustomFieldModelWithDefaults() *RequestCustomFieldModel {
	this := RequestCustomFieldModel{}
	return &this
}

// GetId returns the Id field value
func (o *RequestCustomFieldModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RequestCustomFieldModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RequestCustomFieldModel) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *RequestCustomFieldModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RequestCustomFieldModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RequestCustomFieldModel) SetType(v string) {
	o.Type = v
}

// GetLabel returns the Label field value
func (o *RequestCustomFieldModel) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *RequestCustomFieldModel) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *RequestCustomFieldModel) SetLabel(v string) {
	o.Label = v
}

// GetPlaceholder returns the Placeholder field value
func (o *RequestCustomFieldModel) GetPlaceholder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Placeholder
}

// GetPlaceholderOk returns a tuple with the Placeholder field value
// and a boolean to check if the value has been set.
func (o *RequestCustomFieldModel) GetPlaceholderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Placeholder, true
}

// SetPlaceholder sets field value
func (o *RequestCustomFieldModel) SetPlaceholder(v string) {
	o.Placeholder = v
}

// GetValues returns the Values field value
func (o *RequestCustomFieldModel) GetValues() []RequestCustomFieldValueModel {
	if o == nil {
		var ret []RequestCustomFieldValueModel
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *RequestCustomFieldModel) GetValuesOk() ([]RequestCustomFieldValueModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *RequestCustomFieldModel) SetValues(v []RequestCustomFieldValueModel) {
	o.Values = v
}

// GetDefault returns the Default field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RequestCustomFieldModel) GetDefault() string {
	if o == nil || IsNil(o.Default.Get()) {
		var ret string
		return ret
	}
	return *o.Default.Get()
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequestCustomFieldModel) GetDefaultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Default.Get(), o.Default.IsSet()
}

// HasDefault returns a boolean if a field has been set.
func (o *RequestCustomFieldModel) HasDefault() bool {
	if o != nil && o.Default.IsSet() {
		return true
	}

	return false
}

// SetDefault gets a reference to the given NullableString and assigns it to the Default field.
func (o *RequestCustomFieldModel) SetDefault(v string) {
	o.Default.Set(&v)
}

// SetDefaultNil sets the value for Default to be an explicit nil
func (o *RequestCustomFieldModel) SetDefaultNil() {
	o.Default.Set(nil)
}

// UnsetDefault ensures that no value is present for Default, not even an explicit nil
func (o *RequestCustomFieldModel) UnsetDefault() {
	o.Default.Unset()
}

// GetRequired returns the Required field value
func (o *RequestCustomFieldModel) GetRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Required
}

// GetRequiredOk returns a tuple with the Required field value
// and a boolean to check if the value has been set.
func (o *RequestCustomFieldModel) GetRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Required, true
}

// SetRequired sets field value
func (o *RequestCustomFieldModel) SetRequired(v bool) {
	o.Required = v
}

func (o RequestCustomFieldModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestCustomFieldModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["label"] = o.Label
	toSerialize["placeholder"] = o.Placeholder
	toSerialize["values"] = o.Values
	if o.Default.IsSet() {
		toSerialize["default"] = o.Default.Get()
	}
	toSerialize["required"] = o.Required
	return toSerialize, nil
}

func (o *RequestCustomFieldModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"label",
		"placeholder",
		"values",
		"required",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestCustomFieldModel := _RequestCustomFieldModel{}

	err = json.Unmarshal(bytes, &varRequestCustomFieldModel)

	if err != nil {
		return err
	}

	*o = RequestCustomFieldModel(varRequestCustomFieldModel)

	return err
}

type NullableRequestCustomFieldModel struct {
	value *RequestCustomFieldModel
	isSet bool
}

func (v NullableRequestCustomFieldModel) Get() *RequestCustomFieldModel {
	return v.value
}

func (v *NullableRequestCustomFieldModel) Set(val *RequestCustomFieldModel) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestCustomFieldModel) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestCustomFieldModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestCustomFieldModel(val *RequestCustomFieldModel) *NullableRequestCustomFieldModel {
	return &NullableRequestCustomFieldModel{value: val, isSet: true}
}

func (v NullableRequestCustomFieldModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestCustomFieldModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
