/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AgentAuthResponseAppModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentAuthResponseAppModel{}

// AgentAuthResponseAppModel struct for AgentAuthResponseAppModel
type AgentAuthResponseAppModel struct {
	AgentId    string `json:"agent_id"`
	AgentToken string `json:"agent_token"`
}

type _AgentAuthResponseAppModel AgentAuthResponseAppModel

// NewAgentAuthResponseAppModel instantiates a new AgentAuthResponseAppModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentAuthResponseAppModel(agentId string, agentToken string) *AgentAuthResponseAppModel {
	this := AgentAuthResponseAppModel{}
	this.AgentId = agentId
	this.AgentToken = agentToken
	return &this
}

// NewAgentAuthResponseAppModelWithDefaults instantiates a new AgentAuthResponseAppModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentAuthResponseAppModelWithDefaults() *AgentAuthResponseAppModel {
	this := AgentAuthResponseAppModel{}
	return &this
}

// GetAgentId returns the AgentId field value
func (o *AgentAuthResponseAppModel) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *AgentAuthResponseAppModel) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *AgentAuthResponseAppModel) SetAgentId(v string) {
	o.AgentId = v
}

// GetAgentToken returns the AgentToken field value
func (o *AgentAuthResponseAppModel) GetAgentToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentToken
}

// GetAgentTokenOk returns a tuple with the AgentToken field value
// and a boolean to check if the value has been set.
func (o *AgentAuthResponseAppModel) GetAgentTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentToken, true
}

// SetAgentToken sets field value
func (o *AgentAuthResponseAppModel) SetAgentToken(v string) {
	o.AgentToken = v
}

func (o AgentAuthResponseAppModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentAuthResponseAppModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_id"] = o.AgentId
	toSerialize["agent_token"] = o.AgentToken
	return toSerialize, nil
}

func (o *AgentAuthResponseAppModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_id",
		"agent_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentAuthResponseAppModel := _AgentAuthResponseAppModel{}

	err = json.Unmarshal(bytes, &varAgentAuthResponseAppModel)

	if err != nil {
		return err
	}

	*o = AgentAuthResponseAppModel(varAgentAuthResponseAppModel)

	return err
}

type NullableAgentAuthResponseAppModel struct {
	value *AgentAuthResponseAppModel
	isSet bool
}

func (v NullableAgentAuthResponseAppModel) Get() *AgentAuthResponseAppModel {
	return v.value
}

func (v *NullableAgentAuthResponseAppModel) Set(val *AgentAuthResponseAppModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentAuthResponseAppModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentAuthResponseAppModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentAuthResponseAppModel(val *AgentAuthResponseAppModel) *NullableAgentAuthResponseAppModel {
	return &NullableAgentAuthResponseAppModel{value: val, isSet: true}
}

func (v NullableAgentAuthResponseAppModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentAuthResponseAppModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
