/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AssistantMessageClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantMessageClientModel{}

// AssistantMessageClientModel struct for AssistantMessageClientModel
type AssistantMessageClientModel struct {
	Id             string         `json:"id"`
	MessageOrdinal int32          `json:"message_ordinal"`
	Role           string         `json:"role"`
	Feedback       NullableString `json:"feedback,omitempty"`
	// ISO 8601 formatted date-time
	CreatedDate time.Time                         `json:"created_date"`
	Data        []AssistantMessageDataClientModel `json:"data"`
}

type _AssistantMessageClientModel AssistantMessageClientModel

// NewAssistantMessageClientModel instantiates a new AssistantMessageClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantMessageClientModel(id string, messageOrdinal int32, role string, createdDate time.Time, data []AssistantMessageDataClientModel) *AssistantMessageClientModel {
	this := AssistantMessageClientModel{}
	this.Id = id
	this.MessageOrdinal = messageOrdinal
	this.Role = role
	this.CreatedDate = createdDate
	this.Data = data
	return &this
}

// NewAssistantMessageClientModelWithDefaults instantiates a new AssistantMessageClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantMessageClientModelWithDefaults() *AssistantMessageClientModel {
	this := AssistantMessageClientModel{}
	return &this
}

// GetId returns the Id field value
func (o *AssistantMessageClientModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageClientModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AssistantMessageClientModel) SetId(v string) {
	o.Id = v
}

// GetMessageOrdinal returns the MessageOrdinal field value
func (o *AssistantMessageClientModel) GetMessageOrdinal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MessageOrdinal
}

// GetMessageOrdinalOk returns a tuple with the MessageOrdinal field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageClientModel) GetMessageOrdinalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageOrdinal, true
}

// SetMessageOrdinal sets field value
func (o *AssistantMessageClientModel) SetMessageOrdinal(v int32) {
	o.MessageOrdinal = v
}

// GetRole returns the Role field value
func (o *AssistantMessageClientModel) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageClientModel) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *AssistantMessageClientModel) SetRole(v string) {
	o.Role = v
}

// GetFeedback returns the Feedback field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageClientModel) GetFeedback() string {
	if o == nil || IsNil(o.Feedback.Get()) {
		var ret string
		return ret
	}
	return *o.Feedback.Get()
}

// GetFeedbackOk returns a tuple with the Feedback field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageClientModel) GetFeedbackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Feedback.Get(), o.Feedback.IsSet()
}

// HasFeedback returns a boolean if a field has been set.
func (o *AssistantMessageClientModel) HasFeedback() bool {
	if o != nil && o.Feedback.IsSet() {
		return true
	}

	return false
}

// SetFeedback gets a reference to the given NullableString and assigns it to the Feedback field.
func (o *AssistantMessageClientModel) SetFeedback(v string) {
	o.Feedback.Set(&v)
}

// SetFeedbackNil sets the value for Feedback to be an explicit nil
func (o *AssistantMessageClientModel) SetFeedbackNil() {
	o.Feedback.Set(nil)
}

// UnsetFeedback ensures that no value is present for Feedback, not even an explicit nil
func (o *AssistantMessageClientModel) UnsetFeedback() {
	o.Feedback.Unset()
}

// GetCreatedDate returns the CreatedDate field value
func (o *AssistantMessageClientModel) GetCreatedDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageClientModel) GetCreatedDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedDate, true
}

// SetCreatedDate sets field value
func (o *AssistantMessageClientModel) SetCreatedDate(v time.Time) {
	o.CreatedDate = v
}

// GetData returns the Data field value
func (o *AssistantMessageClientModel) GetData() []AssistantMessageDataClientModel {
	if o == nil {
		var ret []AssistantMessageDataClientModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageClientModel) GetDataOk() ([]AssistantMessageDataClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AssistantMessageClientModel) SetData(v []AssistantMessageDataClientModel) {
	o.Data = v
}

func (o AssistantMessageClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantMessageClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["message_ordinal"] = o.MessageOrdinal
	toSerialize["role"] = o.Role
	if o.Feedback.IsSet() {
		toSerialize["feedback"] = o.Feedback.Get()
	}
	toSerialize["created_date"] = o.CreatedDate
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AssistantMessageClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"message_ordinal",
		"role",
		"created_date",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssistantMessageClientModel := _AssistantMessageClientModel{}

	err = json.Unmarshal(bytes, &varAssistantMessageClientModel)

	if err != nil {
		return err
	}

	*o = AssistantMessageClientModel(varAssistantMessageClientModel)

	return err
}

type NullableAssistantMessageClientModel struct {
	value *AssistantMessageClientModel
	isSet bool
}

func (v NullableAssistantMessageClientModel) Get() *AssistantMessageClientModel {
	return v.value
}

func (v *NullableAssistantMessageClientModel) Set(val *AssistantMessageClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantMessageClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantMessageClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantMessageClientModel(val *AssistantMessageClientModel) *NullableAssistantMessageClientModel {
	return &NullableAssistantMessageClientModel{value: val, isSet: true}
}

func (v NullableAssistantMessageClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantMessageClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
