/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the InstructionClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstructionClientModel{}

// InstructionClientModel struct for InstructionClientModel
type InstructionClientModel struct {
	Plain         string         `json:"plain"`
	Markdown      string         `json:"markdown"`
	CustomMessage NullableString `json:"custom_message,omitempty"`
}

type _InstructionClientModel InstructionClientModel

// NewInstructionClientModel instantiates a new InstructionClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstructionClientModel(plain string, markdown string) *InstructionClientModel {
	this := InstructionClientModel{}
	this.Plain = plain
	this.Markdown = markdown
	return &this
}

// NewInstructionClientModelWithDefaults instantiates a new InstructionClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstructionClientModelWithDefaults() *InstructionClientModel {
	this := InstructionClientModel{}
	return &this
}

// GetPlain returns the Plain field value
func (o *InstructionClientModel) GetPlain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plain
}

// GetPlainOk returns a tuple with the Plain field value
// and a boolean to check if the value has been set.
func (o *InstructionClientModel) GetPlainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plain, true
}

// SetPlain sets field value
func (o *InstructionClientModel) SetPlain(v string) {
	o.Plain = v
}

// GetMarkdown returns the Markdown field value
func (o *InstructionClientModel) GetMarkdown() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Markdown
}

// GetMarkdownOk returns a tuple with the Markdown field value
// and a boolean to check if the value has been set.
func (o *InstructionClientModel) GetMarkdownOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Markdown, true
}

// SetMarkdown sets field value
func (o *InstructionClientModel) SetMarkdown(v string) {
	o.Markdown = v
}

// GetCustomMessage returns the CustomMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstructionClientModel) GetCustomMessage() string {
	if o == nil || IsNil(o.CustomMessage.Get()) {
		var ret string
		return ret
	}
	return *o.CustomMessage.Get()
}

// GetCustomMessageOk returns a tuple with the CustomMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstructionClientModel) GetCustomMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomMessage.Get(), o.CustomMessage.IsSet()
}

// HasCustomMessage returns a boolean if a field has been set.
func (o *InstructionClientModel) HasCustomMessage() bool {
	if o != nil && o.CustomMessage.IsSet() {
		return true
	}

	return false
}

// SetCustomMessage gets a reference to the given NullableString and assigns it to the CustomMessage field.
func (o *InstructionClientModel) SetCustomMessage(v string) {
	o.CustomMessage.Set(&v)
}

// SetCustomMessageNil sets the value for CustomMessage to be an explicit nil
func (o *InstructionClientModel) SetCustomMessageNil() {
	o.CustomMessage.Set(nil)
}

// UnsetCustomMessage ensures that no value is present for CustomMessage, not even an explicit nil
func (o *InstructionClientModel) UnsetCustomMessage() {
	o.CustomMessage.Unset()
}

func (o InstructionClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstructionClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plain"] = o.Plain
	toSerialize["markdown"] = o.Markdown
	if o.CustomMessage.IsSet() {
		toSerialize["custom_message"] = o.CustomMessage.Get()
	}
	return toSerialize, nil
}

func (o *InstructionClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plain",
		"markdown",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstructionClientModel := _InstructionClientModel{}

	err = json.Unmarshal(bytes, &varInstructionClientModel)

	if err != nil {
		return err
	}

	*o = InstructionClientModel(varInstructionClientModel)

	return err
}

type NullableInstructionClientModel struct {
	value *InstructionClientModel
	isSet bool
}

func (v NullableInstructionClientModel) Get() *InstructionClientModel {
	return v.value
}

func (v *NullableInstructionClientModel) Set(val *InstructionClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableInstructionClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableInstructionClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstructionClientModel(val *InstructionClientModel) *NullableInstructionClientModel {
	return &NullableInstructionClientModel{value: val, isSet: true}
}

func (v NullableInstructionClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstructionClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
