/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the JustificationValidationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JustificationValidationResponse{}

// JustificationValidationResponse struct for JustificationValidationResponse
type JustificationValidationResponse struct {
	DescribesTask            bool `json:"describes_task"`
	JustifiesPermissionLevel bool `json:"justifies_permission_level"`
	HasTicketIdUrl           bool `json:"has_ticket_id_url"`
}

type _JustificationValidationResponse JustificationValidationResponse

// NewJustificationValidationResponse instantiates a new JustificationValidationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJustificationValidationResponse(describesTask bool, justifiesPermissionLevel bool, hasTicketIdUrl bool) *JustificationValidationResponse {
	this := JustificationValidationResponse{}
	this.DescribesTask = describesTask
	this.JustifiesPermissionLevel = justifiesPermissionLevel
	this.HasTicketIdUrl = hasTicketIdUrl
	return &this
}

// NewJustificationValidationResponseWithDefaults instantiates a new JustificationValidationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJustificationValidationResponseWithDefaults() *JustificationValidationResponse {
	this := JustificationValidationResponse{}
	return &this
}

// GetDescribesTask returns the DescribesTask field value
func (o *JustificationValidationResponse) GetDescribesTask() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DescribesTask
}

// GetDescribesTaskOk returns a tuple with the DescribesTask field value
// and a boolean to check if the value has been set.
func (o *JustificationValidationResponse) GetDescribesTaskOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DescribesTask, true
}

// SetDescribesTask sets field value
func (o *JustificationValidationResponse) SetDescribesTask(v bool) {
	o.DescribesTask = v
}

// GetJustifiesPermissionLevel returns the JustifiesPermissionLevel field value
func (o *JustificationValidationResponse) GetJustifiesPermissionLevel() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.JustifiesPermissionLevel
}

// GetJustifiesPermissionLevelOk returns a tuple with the JustifiesPermissionLevel field value
// and a boolean to check if the value has been set.
func (o *JustificationValidationResponse) GetJustifiesPermissionLevelOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JustifiesPermissionLevel, true
}

// SetJustifiesPermissionLevel sets field value
func (o *JustificationValidationResponse) SetJustifiesPermissionLevel(v bool) {
	o.JustifiesPermissionLevel = v
}

// GetHasTicketIdUrl returns the HasTicketIdUrl field value
func (o *JustificationValidationResponse) GetHasTicketIdUrl() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasTicketIdUrl
}

// GetHasTicketIdUrlOk returns a tuple with the HasTicketIdUrl field value
// and a boolean to check if the value has been set.
func (o *JustificationValidationResponse) GetHasTicketIdUrlOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasTicketIdUrl, true
}

// SetHasTicketIdUrl sets field value
func (o *JustificationValidationResponse) SetHasTicketIdUrl(v bool) {
	o.HasTicketIdUrl = v
}

func (o JustificationValidationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JustificationValidationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["describes_task"] = o.DescribesTask
	toSerialize["justifies_permission_level"] = o.JustifiesPermissionLevel
	toSerialize["has_ticket_id_url"] = o.HasTicketIdUrl
	return toSerialize, nil
}

func (o *JustificationValidationResponse) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"describes_task",
		"justifies_permission_level",
		"has_ticket_id_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJustificationValidationResponse := _JustificationValidationResponse{}

	err = json.Unmarshal(bytes, &varJustificationValidationResponse)

	if err != nil {
		return err
	}

	*o = JustificationValidationResponse(varJustificationValidationResponse)

	return err
}

type NullableJustificationValidationResponse struct {
	value *JustificationValidationResponse
	isSet bool
}

func (v NullableJustificationValidationResponse) Get() *JustificationValidationResponse {
	return v.value
}

func (v *NullableJustificationValidationResponse) Set(val *JustificationValidationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJustificationValidationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJustificationValidationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJustificationValidationResponse(val *JustificationValidationResponse) *NullableJustificationValidationResponse {
	return &NullableJustificationValidationResponse{value: val, isSet: true}
}

func (v NullableJustificationValidationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJustificationValidationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
