/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessSessionDetailsClientModelLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessSessionDetailsClientModelLink{}

// AccessSessionDetailsClientModelLink struct for AccessSessionDetailsClientModelLink
type AccessSessionDetailsClientModelLink struct {
	Url   string         `json:"url"`
	Title NullableString `json:"title,omitempty"`
}

type _AccessSessionDetailsClientModelLink AccessSessionDetailsClientModelLink

// NewAccessSessionDetailsClientModelLink instantiates a new AccessSessionDetailsClientModelLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessSessionDetailsClientModelLink(url string) *AccessSessionDetailsClientModelLink {
	this := AccessSessionDetailsClientModelLink{}
	this.Url = url
	return &this
}

// NewAccessSessionDetailsClientModelLinkWithDefaults instantiates a new AccessSessionDetailsClientModelLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessSessionDetailsClientModelLinkWithDefaults() *AccessSessionDetailsClientModelLink {
	this := AccessSessionDetailsClientModelLink{}
	return &this
}

// GetUrl returns the Url field value
func (o *AccessSessionDetailsClientModelLink) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *AccessSessionDetailsClientModelLink) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *AccessSessionDetailsClientModelLink) SetUrl(v string) {
	o.Url = v
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccessSessionDetailsClientModelLink) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccessSessionDetailsClientModelLink) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *AccessSessionDetailsClientModelLink) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *AccessSessionDetailsClientModelLink) SetTitle(v string) {
	o.Title.Set(&v)
}

// SetTitleNil sets the value for Title to be an explicit nil
func (o *AccessSessionDetailsClientModelLink) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *AccessSessionDetailsClientModelLink) UnsetTitle() {
	o.Title.Unset()
}

func (o AccessSessionDetailsClientModelLink) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessSessionDetailsClientModelLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	return toSerialize, nil
}

func (o *AccessSessionDetailsClientModelLink) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessSessionDetailsClientModelLink := _AccessSessionDetailsClientModelLink{}

	err = json.Unmarshal(bytes, &varAccessSessionDetailsClientModelLink)

	if err != nil {
		return err
	}

	*o = AccessSessionDetailsClientModelLink(varAccessSessionDetailsClientModelLink)

	return err
}

type NullableAccessSessionDetailsClientModelLink struct {
	value *AccessSessionDetailsClientModelLink
	isSet bool
}

func (v NullableAccessSessionDetailsClientModelLink) Get() *AccessSessionDetailsClientModelLink {
	return v.value
}

func (v *NullableAccessSessionDetailsClientModelLink) Set(val *AccessSessionDetailsClientModelLink) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessSessionDetailsClientModelLink) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessSessionDetailsClientModelLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessSessionDetailsClientModelLink(val *AccessSessionDetailsClientModelLink) *NullableAccessSessionDetailsClientModelLink {
	return &NullableAccessSessionDetailsClientModelLink{value: val, isSet: true}
}

func (v NullableAccessSessionDetailsClientModelLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessSessionDetailsClientModelLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
