/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MessageDataImageClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageDataImageClientModel{}

// MessageDataImageClientModel struct for MessageDataImageClientModel
type MessageDataImageClientModel struct {
	Link string `json:"link"`
}

type _MessageDataImageClientModel MessageDataImageClientModel

// NewMessageDataImageClientModel instantiates a new MessageDataImageClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageDataImageClientModel(link string) *MessageDataImageClientModel {
	this := MessageDataImageClientModel{}
	this.Link = link
	return &this
}

// NewMessageDataImageClientModelWithDefaults instantiates a new MessageDataImageClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageDataImageClientModelWithDefaults() *MessageDataImageClientModel {
	this := MessageDataImageClientModel{}
	return &this
}

// GetLink returns the Link field value
func (o *MessageDataImageClientModel) GetLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Link
}

// GetLinkOk returns a tuple with the Link field value
// and a boolean to check if the value has been set.
func (o *MessageDataImageClientModel) GetLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Link, true
}

// SetLink sets field value
func (o *MessageDataImageClientModel) SetLink(v string) {
	o.Link = v
}

func (o MessageDataImageClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageDataImageClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["link"] = o.Link
	return toSerialize, nil
}

func (o *MessageDataImageClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"link",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageDataImageClientModel := _MessageDataImageClientModel{}

	err = json.Unmarshal(bytes, &varMessageDataImageClientModel)

	if err != nil {
		return err
	}

	*o = MessageDataImageClientModel(varMessageDataImageClientModel)

	return err
}

type NullableMessageDataImageClientModel struct {
	value *MessageDataImageClientModel
	isSet bool
}

func (v NullableMessageDataImageClientModel) Get() *MessageDataImageClientModel {
	return v.value
}

func (v *NullableMessageDataImageClientModel) Set(val *MessageDataImageClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageDataImageClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageDataImageClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageDataImageClientModel(val *MessageDataImageClientModel) *NullableMessageDataImageClientModel {
	return &NullableMessageDataImageClientModel{value: val, isSet: true}
}

func (v NullableMessageDataImageClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageDataImageClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
