/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessElevatedClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessElevatedClientModel{}

// AccessElevatedClientModel struct for AccessElevatedClientModel
type AccessElevatedClientModel struct {
	AccessRequestId string `json:"access_request_id"`
}

type _AccessElevatedClientModel AccessElevatedClientModel

// NewAccessElevatedClientModel instantiates a new AccessElevatedClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessElevatedClientModel(accessRequestId string) *AccessElevatedClientModel {
	this := AccessElevatedClientModel{}
	this.AccessRequestId = accessRequestId
	return &this
}

// NewAccessElevatedClientModelWithDefaults instantiates a new AccessElevatedClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessElevatedClientModelWithDefaults() *AccessElevatedClientModel {
	this := AccessElevatedClientModel{}
	return &this
}

// GetAccessRequestId returns the AccessRequestId field value
func (o *AccessElevatedClientModel) GetAccessRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessRequestId
}

// GetAccessRequestIdOk returns a tuple with the AccessRequestId field value
// and a boolean to check if the value has been set.
func (o *AccessElevatedClientModel) GetAccessRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessRequestId, true
}

// SetAccessRequestId sets field value
func (o *AccessElevatedClientModel) SetAccessRequestId(v string) {
	o.AccessRequestId = v
}

func (o AccessElevatedClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessElevatedClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_request_id"] = o.AccessRequestId
	return toSerialize, nil
}

func (o *AccessElevatedClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessElevatedClientModel := _AccessElevatedClientModel{}

	err = json.Unmarshal(bytes, &varAccessElevatedClientModel)

	if err != nil {
		return err
	}

	*o = AccessElevatedClientModel(varAccessElevatedClientModel)

	return err
}

type NullableAccessElevatedClientModel struct {
	value *AccessElevatedClientModel
	isSet bool
}

func (v NullableAccessElevatedClientModel) Get() *AccessElevatedClientModel {
	return v.value
}

func (v *NullableAccessElevatedClientModel) Set(val *AccessElevatedClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessElevatedClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessElevatedClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessElevatedClientModel(val *AccessElevatedClientModel) *NullableAccessElevatedClientModel {
	return &NullableAccessElevatedClientModel{value: val, isSet: true}
}

func (v NullableAccessElevatedClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessElevatedClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
