/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SessionEventClientModelToolActivity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionEventClientModelToolActivity{}

// SessionEventClientModelToolActivity struct for SessionEventClientModelToolActivity
type SessionEventClientModelToolActivity struct {
	EventGroupId        string         `json:"event_group_id"`
	ToolExecutionCount  int32          `json:"tool_execution_count"`
	ToolName            string         `json:"tool_name"`
	IntentAction        NullableString `json:"intent_action,omitempty"`
	EnforcementDecision NullableString `json:"enforcement_decision,omitempty"`
	McpServerName       NullableString `json:"mcp_server_name,omitempty"`
	ResourceId          NullableString `json:"resource_id,omitempty"`
}

type _SessionEventClientModelToolActivity SessionEventClientModelToolActivity

// NewSessionEventClientModelToolActivity instantiates a new SessionEventClientModelToolActivity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionEventClientModelToolActivity(eventGroupId string, toolExecutionCount int32, toolName string) *SessionEventClientModelToolActivity {
	this := SessionEventClientModelToolActivity{}
	this.EventGroupId = eventGroupId
	this.ToolExecutionCount = toolExecutionCount
	this.ToolName = toolName
	return &this
}

// NewSessionEventClientModelToolActivityWithDefaults instantiates a new SessionEventClientModelToolActivity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionEventClientModelToolActivityWithDefaults() *SessionEventClientModelToolActivity {
	this := SessionEventClientModelToolActivity{}
	return &this
}

// GetEventGroupId returns the EventGroupId field value
func (o *SessionEventClientModelToolActivity) GetEventGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventGroupId
}

// GetEventGroupIdOk returns a tuple with the EventGroupId field value
// and a boolean to check if the value has been set.
func (o *SessionEventClientModelToolActivity) GetEventGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventGroupId, true
}

// SetEventGroupId sets field value
func (o *SessionEventClientModelToolActivity) SetEventGroupId(v string) {
	o.EventGroupId = v
}

// GetToolExecutionCount returns the ToolExecutionCount field value
func (o *SessionEventClientModelToolActivity) GetToolExecutionCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ToolExecutionCount
}

// GetToolExecutionCountOk returns a tuple with the ToolExecutionCount field value
// and a boolean to check if the value has been set.
func (o *SessionEventClientModelToolActivity) GetToolExecutionCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToolExecutionCount, true
}

// SetToolExecutionCount sets field value
func (o *SessionEventClientModelToolActivity) SetToolExecutionCount(v int32) {
	o.ToolExecutionCount = v
}

// GetToolName returns the ToolName field value
func (o *SessionEventClientModelToolActivity) GetToolName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToolName
}

// GetToolNameOk returns a tuple with the ToolName field value
// and a boolean to check if the value has been set.
func (o *SessionEventClientModelToolActivity) GetToolNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToolName, true
}

// SetToolName sets field value
func (o *SessionEventClientModelToolActivity) SetToolName(v string) {
	o.ToolName = v
}

// GetIntentAction returns the IntentAction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionEventClientModelToolActivity) GetIntentAction() string {
	if o == nil || IsNil(o.IntentAction.Get()) {
		var ret string
		return ret
	}
	return *o.IntentAction.Get()
}

// GetIntentActionOk returns a tuple with the IntentAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionEventClientModelToolActivity) GetIntentActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntentAction.Get(), o.IntentAction.IsSet()
}

// HasIntentAction returns a boolean if a field has been set.
func (o *SessionEventClientModelToolActivity) HasIntentAction() bool {
	if o != nil && o.IntentAction.IsSet() {
		return true
	}

	return false
}

// SetIntentAction gets a reference to the given NullableString and assigns it to the IntentAction field.
func (o *SessionEventClientModelToolActivity) SetIntentAction(v string) {
	o.IntentAction.Set(&v)
}

// SetIntentActionNil sets the value for IntentAction to be an explicit nil
func (o *SessionEventClientModelToolActivity) SetIntentActionNil() {
	o.IntentAction.Set(nil)
}

// UnsetIntentAction ensures that no value is present for IntentAction, not even an explicit nil
func (o *SessionEventClientModelToolActivity) UnsetIntentAction() {
	o.IntentAction.Unset()
}

// GetEnforcementDecision returns the EnforcementDecision field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionEventClientModelToolActivity) GetEnforcementDecision() string {
	if o == nil || IsNil(o.EnforcementDecision.Get()) {
		var ret string
		return ret
	}
	return *o.EnforcementDecision.Get()
}

// GetEnforcementDecisionOk returns a tuple with the EnforcementDecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionEventClientModelToolActivity) GetEnforcementDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnforcementDecision.Get(), o.EnforcementDecision.IsSet()
}

// HasEnforcementDecision returns a boolean if a field has been set.
func (o *SessionEventClientModelToolActivity) HasEnforcementDecision() bool {
	if o != nil && o.EnforcementDecision.IsSet() {
		return true
	}

	return false
}

// SetEnforcementDecision gets a reference to the given NullableString and assigns it to the EnforcementDecision field.
func (o *SessionEventClientModelToolActivity) SetEnforcementDecision(v string) {
	o.EnforcementDecision.Set(&v)
}

// SetEnforcementDecisionNil sets the value for EnforcementDecision to be an explicit nil
func (o *SessionEventClientModelToolActivity) SetEnforcementDecisionNil() {
	o.EnforcementDecision.Set(nil)
}

// UnsetEnforcementDecision ensures that no value is present for EnforcementDecision, not even an explicit nil
func (o *SessionEventClientModelToolActivity) UnsetEnforcementDecision() {
	o.EnforcementDecision.Unset()
}

// GetMcpServerName returns the McpServerName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionEventClientModelToolActivity) GetMcpServerName() string {
	if o == nil || IsNil(o.McpServerName.Get()) {
		var ret string
		return ret
	}
	return *o.McpServerName.Get()
}

// GetMcpServerNameOk returns a tuple with the McpServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionEventClientModelToolActivity) GetMcpServerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.McpServerName.Get(), o.McpServerName.IsSet()
}

// HasMcpServerName returns a boolean if a field has been set.
func (o *SessionEventClientModelToolActivity) HasMcpServerName() bool {
	if o != nil && o.McpServerName.IsSet() {
		return true
	}

	return false
}

// SetMcpServerName gets a reference to the given NullableString and assigns it to the McpServerName field.
func (o *SessionEventClientModelToolActivity) SetMcpServerName(v string) {
	o.McpServerName.Set(&v)
}

// SetMcpServerNameNil sets the value for McpServerName to be an explicit nil
func (o *SessionEventClientModelToolActivity) SetMcpServerNameNil() {
	o.McpServerName.Set(nil)
}

// UnsetMcpServerName ensures that no value is present for McpServerName, not even an explicit nil
func (o *SessionEventClientModelToolActivity) UnsetMcpServerName() {
	o.McpServerName.Unset()
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionEventClientModelToolActivity) GetResourceId() string {
	if o == nil || IsNil(o.ResourceId.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceId.Get()
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionEventClientModelToolActivity) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceId.Get(), o.ResourceId.IsSet()
}

// HasResourceId returns a boolean if a field has been set.
func (o *SessionEventClientModelToolActivity) HasResourceId() bool {
	if o != nil && o.ResourceId.IsSet() {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given NullableString and assigns it to the ResourceId field.
func (o *SessionEventClientModelToolActivity) SetResourceId(v string) {
	o.ResourceId.Set(&v)
}

// SetResourceIdNil sets the value for ResourceId to be an explicit nil
func (o *SessionEventClientModelToolActivity) SetResourceIdNil() {
	o.ResourceId.Set(nil)
}

// UnsetResourceId ensures that no value is present for ResourceId, not even an explicit nil
func (o *SessionEventClientModelToolActivity) UnsetResourceId() {
	o.ResourceId.Unset()
}

func (o SessionEventClientModelToolActivity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionEventClientModelToolActivity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_group_id"] = o.EventGroupId
	toSerialize["tool_execution_count"] = o.ToolExecutionCount
	toSerialize["tool_name"] = o.ToolName
	if o.IntentAction.IsSet() {
		toSerialize["intent_action"] = o.IntentAction.Get()
	}
	if o.EnforcementDecision.IsSet() {
		toSerialize["enforcement_decision"] = o.EnforcementDecision.Get()
	}
	if o.McpServerName.IsSet() {
		toSerialize["mcp_server_name"] = o.McpServerName.Get()
	}
	if o.ResourceId.IsSet() {
		toSerialize["resource_id"] = o.ResourceId.Get()
	}
	return toSerialize, nil
}

func (o *SessionEventClientModelToolActivity) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_group_id",
		"tool_execution_count",
		"tool_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionEventClientModelToolActivity := _SessionEventClientModelToolActivity{}

	err = json.Unmarshal(bytes, &varSessionEventClientModelToolActivity)

	if err != nil {
		return err
	}

	*o = SessionEventClientModelToolActivity(varSessionEventClientModelToolActivity)

	return err
}

type NullableSessionEventClientModelToolActivity struct {
	value *SessionEventClientModelToolActivity
	isSet bool
}

func (v NullableSessionEventClientModelToolActivity) Get() *SessionEventClientModelToolActivity {
	return v.value
}

func (v *NullableSessionEventClientModelToolActivity) Set(val *SessionEventClientModelToolActivity) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionEventClientModelToolActivity) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionEventClientModelToolActivity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionEventClientModelToolActivity(val *SessionEventClientModelToolActivity) *NullableSessionEventClientModelToolActivity {
	return &NullableSessionEventClientModelToolActivity{value: val, isSet: true}
}

func (v NullableSessionEventClientModelToolActivity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionEventClientModelToolActivity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
