/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the McpServerClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McpServerClientModel{}

// McpServerClientModel struct for McpServerClientModel
type McpServerClientModel struct {
	Id            string                              `json:"id"`
	Type          string                              `json:"type"`
	Name          string                              `json:"name"`
	CatalogType   NullableString                      `json:"catalog_type,omitempty"`
	ServerConfig  McpServerConfigAppModel             `json:"server_config"`
	ResourceTypes []string                            `json:"resource_types"`
	BlockedTools  []string                            `json:"blocked_tools"`
	ToolIntents   map[string]McpToolIntentClientModel `json:"tool_intents,omitempty"`
}

type _McpServerClientModel McpServerClientModel

// NewMcpServerClientModel instantiates a new McpServerClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcpServerClientModel(id string, type_ string, name string, serverConfig McpServerConfigAppModel, resourceTypes []string, blockedTools []string) *McpServerClientModel {
	this := McpServerClientModel{}
	this.Id = id
	this.Type = type_
	this.Name = name
	this.ServerConfig = serverConfig
	this.ResourceTypes = resourceTypes
	this.BlockedTools = blockedTools
	return &this
}

// NewMcpServerClientModelWithDefaults instantiates a new McpServerClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcpServerClientModelWithDefaults() *McpServerClientModel {
	this := McpServerClientModel{}
	return &this
}

// GetId returns the Id field value
func (o *McpServerClientModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *McpServerClientModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *McpServerClientModel) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *McpServerClientModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *McpServerClientModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *McpServerClientModel) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *McpServerClientModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *McpServerClientModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *McpServerClientModel) SetName(v string) {
	o.Name = v
}

// GetCatalogType returns the CatalogType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *McpServerClientModel) GetCatalogType() string {
	if o == nil || IsNil(o.CatalogType.Get()) {
		var ret string
		return ret
	}
	return *o.CatalogType.Get()
}

// GetCatalogTypeOk returns a tuple with the CatalogType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *McpServerClientModel) GetCatalogTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CatalogType.Get(), o.CatalogType.IsSet()
}

// HasCatalogType returns a boolean if a field has been set.
func (o *McpServerClientModel) HasCatalogType() bool {
	if o != nil && o.CatalogType.IsSet() {
		return true
	}

	return false
}

// SetCatalogType gets a reference to the given NullableString and assigns it to the CatalogType field.
func (o *McpServerClientModel) SetCatalogType(v string) {
	o.CatalogType.Set(&v)
}

// SetCatalogTypeNil sets the value for CatalogType to be an explicit nil
func (o *McpServerClientModel) SetCatalogTypeNil() {
	o.CatalogType.Set(nil)
}

// UnsetCatalogType ensures that no value is present for CatalogType, not even an explicit nil
func (o *McpServerClientModel) UnsetCatalogType() {
	o.CatalogType.Unset()
}

// GetServerConfig returns the ServerConfig field value
func (o *McpServerClientModel) GetServerConfig() McpServerConfigAppModel {
	if o == nil {
		var ret McpServerConfigAppModel
		return ret
	}

	return o.ServerConfig
}

// GetServerConfigOk returns a tuple with the ServerConfig field value
// and a boolean to check if the value has been set.
func (o *McpServerClientModel) GetServerConfigOk() (*McpServerConfigAppModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerConfig, true
}

// SetServerConfig sets field value
func (o *McpServerClientModel) SetServerConfig(v McpServerConfigAppModel) {
	o.ServerConfig = v
}

// GetResourceTypes returns the ResourceTypes field value
func (o *McpServerClientModel) GetResourceTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ResourceTypes
}

// GetResourceTypesOk returns a tuple with the ResourceTypes field value
// and a boolean to check if the value has been set.
func (o *McpServerClientModel) GetResourceTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceTypes, true
}

// SetResourceTypes sets field value
func (o *McpServerClientModel) SetResourceTypes(v []string) {
	o.ResourceTypes = v
}

// GetBlockedTools returns the BlockedTools field value
func (o *McpServerClientModel) GetBlockedTools() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BlockedTools
}

// GetBlockedToolsOk returns a tuple with the BlockedTools field value
// and a boolean to check if the value has been set.
func (o *McpServerClientModel) GetBlockedToolsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockedTools, true
}

// SetBlockedTools sets field value
func (o *McpServerClientModel) SetBlockedTools(v []string) {
	o.BlockedTools = v
}

// GetToolIntents returns the ToolIntents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *McpServerClientModel) GetToolIntents() map[string]McpToolIntentClientModel {
	if o == nil {
		var ret map[string]McpToolIntentClientModel
		return ret
	}
	return o.ToolIntents
}

// GetToolIntentsOk returns a tuple with the ToolIntents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *McpServerClientModel) GetToolIntentsOk() (*map[string]McpToolIntentClientModel, bool) {
	if o == nil || IsNil(o.ToolIntents) {
		return nil, false
	}
	return &o.ToolIntents, true
}

// HasToolIntents returns a boolean if a field has been set.
func (o *McpServerClientModel) HasToolIntents() bool {
	if o != nil && IsNil(o.ToolIntents) {
		return true
	}

	return false
}

// SetToolIntents gets a reference to the given map[string]McpToolIntentClientModel and assigns it to the ToolIntents field.
func (o *McpServerClientModel) SetToolIntents(v map[string]McpToolIntentClientModel) {
	o.ToolIntents = v
}

func (o McpServerClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McpServerClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	if o.CatalogType.IsSet() {
		toSerialize["catalog_type"] = o.CatalogType.Get()
	}
	toSerialize["server_config"] = o.ServerConfig
	toSerialize["resource_types"] = o.ResourceTypes
	toSerialize["blocked_tools"] = o.BlockedTools
	if o.ToolIntents != nil {
		toSerialize["tool_intents"] = o.ToolIntents
	}
	return toSerialize, nil
}

func (o *McpServerClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"name",
		"server_config",
		"resource_types",
		"blocked_tools",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMcpServerClientModel := _McpServerClientModel{}

	err = json.Unmarshal(bytes, &varMcpServerClientModel)

	if err != nil {
		return err
	}

	*o = McpServerClientModel(varMcpServerClientModel)

	return err
}

type NullableMcpServerClientModel struct {
	value *McpServerClientModel
	isSet bool
}

func (v NullableMcpServerClientModel) Get() *McpServerClientModel {
	return v.value
}

func (v *NullableMcpServerClientModel) Set(val *McpServerClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMcpServerClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMcpServerClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcpServerClientModel(val *McpServerClientModel) *NullableMcpServerClientModel {
	return &NullableMcpServerClientModel{value: val, isSet: true}
}

func (v NullableMcpServerClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcpServerClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
