/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MessageDataMarkdownClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageDataMarkdownClientModel{}

// MessageDataMarkdownClientModel struct for MessageDataMarkdownClientModel
type MessageDataMarkdownClientModel struct {
	Content string `json:"content"`
}

type _MessageDataMarkdownClientModel MessageDataMarkdownClientModel

// NewMessageDataMarkdownClientModel instantiates a new MessageDataMarkdownClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageDataMarkdownClientModel(content string) *MessageDataMarkdownClientModel {
	this := MessageDataMarkdownClientModel{}
	this.Content = content
	return &this
}

// NewMessageDataMarkdownClientModelWithDefaults instantiates a new MessageDataMarkdownClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageDataMarkdownClientModelWithDefaults() *MessageDataMarkdownClientModel {
	this := MessageDataMarkdownClientModel{}
	return &this
}

// GetContent returns the Content field value
func (o *MessageDataMarkdownClientModel) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *MessageDataMarkdownClientModel) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *MessageDataMarkdownClientModel) SetContent(v string) {
	o.Content = v
}

func (o MessageDataMarkdownClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageDataMarkdownClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *MessageDataMarkdownClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageDataMarkdownClientModel := _MessageDataMarkdownClientModel{}

	err = json.Unmarshal(bytes, &varMessageDataMarkdownClientModel)

	if err != nil {
		return err
	}

	*o = MessageDataMarkdownClientModel(varMessageDataMarkdownClientModel)

	return err
}

type NullableMessageDataMarkdownClientModel struct {
	value *MessageDataMarkdownClientModel
	isSet bool
}

func (v NullableMessageDataMarkdownClientModel) Get() *MessageDataMarkdownClientModel {
	return v.value
}

func (v *NullableMessageDataMarkdownClientModel) Set(val *MessageDataMarkdownClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageDataMarkdownClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageDataMarkdownClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageDataMarkdownClientModel(val *MessageDataMarkdownClientModel) *NullableMessageDataMarkdownClientModel {
	return &NullableMessageDataMarkdownClientModel{value: val, isSet: true}
}

func (v NullableMessageDataMarkdownClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageDataMarkdownClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
