/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UserSettingsClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSettingsClientModel{}

// UserSettingsClientModel struct for UserSettingsClientModel
type UserSettingsClientModel struct {
	RequireDurationForAccessRequest bool `json:"require_duration_for_access_request"`
}

type _UserSettingsClientModel UserSettingsClientModel

// NewUserSettingsClientModel instantiates a new UserSettingsClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSettingsClientModel(requireDurationForAccessRequest bool) *UserSettingsClientModel {
	this := UserSettingsClientModel{}
	this.RequireDurationForAccessRequest = requireDurationForAccessRequest
	return &this
}

// NewUserSettingsClientModelWithDefaults instantiates a new UserSettingsClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSettingsClientModelWithDefaults() *UserSettingsClientModel {
	this := UserSettingsClientModel{}
	return &this
}

// GetRequireDurationForAccessRequest returns the RequireDurationForAccessRequest field value
func (o *UserSettingsClientModel) GetRequireDurationForAccessRequest() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequireDurationForAccessRequest
}

// GetRequireDurationForAccessRequestOk returns a tuple with the RequireDurationForAccessRequest field value
// and a boolean to check if the value has been set.
func (o *UserSettingsClientModel) GetRequireDurationForAccessRequestOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequireDurationForAccessRequest, true
}

// SetRequireDurationForAccessRequest sets field value
func (o *UserSettingsClientModel) SetRequireDurationForAccessRequest(v bool) {
	o.RequireDurationForAccessRequest = v
}

func (o UserSettingsClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSettingsClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["require_duration_for_access_request"] = o.RequireDurationForAccessRequest
	return toSerialize, nil
}

func (o *UserSettingsClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"require_duration_for_access_request",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserSettingsClientModel := _UserSettingsClientModel{}

	err = json.Unmarshal(bytes, &varUserSettingsClientModel)

	if err != nil {
		return err
	}

	*o = UserSettingsClientModel(varUserSettingsClientModel)

	return err
}

type NullableUserSettingsClientModel struct {
	value *UserSettingsClientModel
	isSet bool
}

func (v NullableUserSettingsClientModel) Get() *UserSettingsClientModel {
	return v.value
}

func (v *NullableUserSettingsClientModel) Set(val *UserSettingsClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSettingsClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSettingsClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSettingsClientModel(val *UserSettingsClientModel) *NullableUserSettingsClientModel {
	return &NullableUserSettingsClientModel{value: val, isSet: true}
}

func (v NullableUserSettingsClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSettingsClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
