/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessDetailsClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessDetailsClientModel{}

// AccessDetailsClientModel struct for AccessDetailsClientModel
type AccessDetailsClientModel struct {
	Plain               string `json:"plain"`
	Markdown            string `json:"markdown"`
	CanResetCredentials bool   `json:"can_reset_credentials"`
}

type _AccessDetailsClientModel AccessDetailsClientModel

// NewAccessDetailsClientModel instantiates a new AccessDetailsClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessDetailsClientModel(plain string, markdown string, canResetCredentials bool) *AccessDetailsClientModel {
	this := AccessDetailsClientModel{}
	this.Plain = plain
	this.Markdown = markdown
	this.CanResetCredentials = canResetCredentials
	return &this
}

// NewAccessDetailsClientModelWithDefaults instantiates a new AccessDetailsClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessDetailsClientModelWithDefaults() *AccessDetailsClientModel {
	this := AccessDetailsClientModel{}
	return &this
}

// GetPlain returns the Plain field value
func (o *AccessDetailsClientModel) GetPlain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plain
}

// GetPlainOk returns a tuple with the Plain field value
// and a boolean to check if the value has been set.
func (o *AccessDetailsClientModel) GetPlainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plain, true
}

// SetPlain sets field value
func (o *AccessDetailsClientModel) SetPlain(v string) {
	o.Plain = v
}

// GetMarkdown returns the Markdown field value
func (o *AccessDetailsClientModel) GetMarkdown() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Markdown
}

// GetMarkdownOk returns a tuple with the Markdown field value
// and a boolean to check if the value has been set.
func (o *AccessDetailsClientModel) GetMarkdownOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Markdown, true
}

// SetMarkdown sets field value
func (o *AccessDetailsClientModel) SetMarkdown(v string) {
	o.Markdown = v
}

// GetCanResetCredentials returns the CanResetCredentials field value
func (o *AccessDetailsClientModel) GetCanResetCredentials() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanResetCredentials
}

// GetCanResetCredentialsOk returns a tuple with the CanResetCredentials field value
// and a boolean to check if the value has been set.
func (o *AccessDetailsClientModel) GetCanResetCredentialsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanResetCredentials, true
}

// SetCanResetCredentials sets field value
func (o *AccessDetailsClientModel) SetCanResetCredentials(v bool) {
	o.CanResetCredentials = v
}

func (o AccessDetailsClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessDetailsClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plain"] = o.Plain
	toSerialize["markdown"] = o.Markdown
	toSerialize["can_reset_credentials"] = o.CanResetCredentials
	return toSerialize, nil
}

func (o *AccessDetailsClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plain",
		"markdown",
		"can_reset_credentials",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessDetailsClientModel := _AccessDetailsClientModel{}

	err = json.Unmarshal(bytes, &varAccessDetailsClientModel)

	if err != nil {
		return err
	}

	*o = AccessDetailsClientModel(varAccessDetailsClientModel)

	return err
}

type NullableAccessDetailsClientModel struct {
	value *AccessDetailsClientModel
	isSet bool
}

func (v NullableAccessDetailsClientModel) Get() *AccessDetailsClientModel {
	return v.value
}

func (v *NullableAccessDetailsClientModel) Set(val *AccessDetailsClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessDetailsClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessDetailsClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessDetailsClientModel(val *AccessDetailsClientModel) *NullableAccessDetailsClientModel {
	return &NullableAccessDetailsClientModel{value: val, isSet: true}
}

func (v NullableAccessDetailsClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessDetailsClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
