/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AssistantMessageResponseClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantMessageResponseClientModel{}

// AssistantMessageResponseClientModel struct for AssistantMessageResponseClientModel
type AssistantMessageResponseClientModel struct {
	ConversationId string                                       `json:"conversation_id"`
	Message        AssistantMessageClientModel                  `json:"message"`
	Suggestions    []AssistantConversationSuggestionClientModel `json:"suggestions"`
}

type _AssistantMessageResponseClientModel AssistantMessageResponseClientModel

// NewAssistantMessageResponseClientModel instantiates a new AssistantMessageResponseClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantMessageResponseClientModel(conversationId string, message AssistantMessageClientModel, suggestions []AssistantConversationSuggestionClientModel) *AssistantMessageResponseClientModel {
	this := AssistantMessageResponseClientModel{}
	this.ConversationId = conversationId
	this.Message = message
	this.Suggestions = suggestions
	return &this
}

// NewAssistantMessageResponseClientModelWithDefaults instantiates a new AssistantMessageResponseClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantMessageResponseClientModelWithDefaults() *AssistantMessageResponseClientModel {
	this := AssistantMessageResponseClientModel{}
	return &this
}

// GetConversationId returns the ConversationId field value
func (o *AssistantMessageResponseClientModel) GetConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageResponseClientModel) GetConversationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationId, true
}

// SetConversationId sets field value
func (o *AssistantMessageResponseClientModel) SetConversationId(v string) {
	o.ConversationId = v
}

// GetMessage returns the Message field value
func (o *AssistantMessageResponseClientModel) GetMessage() AssistantMessageClientModel {
	if o == nil {
		var ret AssistantMessageClientModel
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageResponseClientModel) GetMessageOk() (*AssistantMessageClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AssistantMessageResponseClientModel) SetMessage(v AssistantMessageClientModel) {
	o.Message = v
}

// GetSuggestions returns the Suggestions field value
func (o *AssistantMessageResponseClientModel) GetSuggestions() []AssistantConversationSuggestionClientModel {
	if o == nil {
		var ret []AssistantConversationSuggestionClientModel
		return ret
	}

	return o.Suggestions
}

// GetSuggestionsOk returns a tuple with the Suggestions field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageResponseClientModel) GetSuggestionsOk() ([]AssistantConversationSuggestionClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Suggestions, true
}

// SetSuggestions sets field value
func (o *AssistantMessageResponseClientModel) SetSuggestions(v []AssistantConversationSuggestionClientModel) {
	o.Suggestions = v
}

func (o AssistantMessageResponseClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantMessageResponseClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["conversation_id"] = o.ConversationId
	toSerialize["message"] = o.Message
	toSerialize["suggestions"] = o.Suggestions
	return toSerialize, nil
}

func (o *AssistantMessageResponseClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conversation_id",
		"message",
		"suggestions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssistantMessageResponseClientModel := _AssistantMessageResponseClientModel{}

	err = json.Unmarshal(bytes, &varAssistantMessageResponseClientModel)

	if err != nil {
		return err
	}

	*o = AssistantMessageResponseClientModel(varAssistantMessageResponseClientModel)

	return err
}

type NullableAssistantMessageResponseClientModel struct {
	value *AssistantMessageResponseClientModel
	isSet bool
}

func (v NullableAssistantMessageResponseClientModel) Get() *AssistantMessageResponseClientModel {
	return v.value
}

func (v *NullableAssistantMessageResponseClientModel) Set(val *AssistantMessageResponseClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantMessageResponseClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantMessageResponseClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantMessageResponseClientModel(val *AssistantMessageResponseClientModel) *NullableAssistantMessageResponseClientModel {
	return &NullableAssistantMessageResponseClientModel{value: val, isSet: true}
}

func (v NullableAssistantMessageResponseClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantMessageResponseClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
