/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AccountClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountClientModel{}

// AccountClientModel struct for AccountClientModel
type AccountClientModel struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Plan string `json:"plan"`
}

type _AccountClientModel AccountClientModel

// NewAccountClientModel instantiates a new AccountClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountClientModel(id string, name string, plan string) *AccountClientModel {
	this := AccountClientModel{}
	this.Id = id
	this.Name = name
	this.Plan = plan
	return &this
}

// NewAccountClientModelWithDefaults instantiates a new AccountClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountClientModelWithDefaults() *AccountClientModel {
	this := AccountClientModel{}
	return &this
}

// GetId returns the Id field value
func (o *AccountClientModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccountClientModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccountClientModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AccountClientModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccountClientModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccountClientModel) SetName(v string) {
	o.Name = v
}

// GetPlan returns the Plan field value
func (o *AccountClientModel) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *AccountClientModel) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *AccountClientModel) SetPlan(v string) {
	o.Plan = v
}

func (o AccountClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["plan"] = o.Plan
	return toSerialize, nil
}

func (o *AccountClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"plan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountClientModel := _AccountClientModel{}

	err = json.Unmarshal(bytes, &varAccountClientModel)

	if err != nil {
		return err
	}

	*o = AccountClientModel(varAccountClientModel)

	return err
}

type NullableAccountClientModel struct {
	value *AccountClientModel
	isSet bool
}

func (v NullableAccountClientModel) Get() *AccountClientModel {
	return v.value
}

func (v *NullableAccountClientModel) Set(val *AccountClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountClientModel(val *AccountClientModel) *NullableAccountClientModel {
	return &NullableAccountClientModel{value: val, isSet: true}
}

func (v NullableAccountClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
