/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RequestAgainClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgainClientModel{}

// RequestAgainClientModel struct for RequestAgainClientModel
type RequestAgainClientModel struct {
	Justification             string            `json:"justification"`
	CustomFields              map[string]string `json:"custom_fields,omitempty"`
	RunPreApprovalValidations NullableBool      `json:"run_pre_approval_validations,omitempty"`
}

type _RequestAgainClientModel RequestAgainClientModel

// NewRequestAgainClientModel instantiates a new RequestAgainClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgainClientModel(justification string) *RequestAgainClientModel {
	this := RequestAgainClientModel{}
	this.Justification = justification
	return &this
}

// NewRequestAgainClientModelWithDefaults instantiates a new RequestAgainClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgainClientModelWithDefaults() *RequestAgainClientModel {
	this := RequestAgainClientModel{}
	return &this
}

// GetJustification returns the Justification field value
func (o *RequestAgainClientModel) GetJustification() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Justification
}

// GetJustificationOk returns a tuple with the Justification field value
// and a boolean to check if the value has been set.
func (o *RequestAgainClientModel) GetJustificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Justification, true
}

// SetJustification sets field value
func (o *RequestAgainClientModel) SetJustification(v string) {
	o.Justification = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RequestAgainClientModel) GetCustomFields() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequestAgainClientModel) GetCustomFieldsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return nil, false
	}
	return &o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *RequestAgainClientModel) HasCustomFields() bool {
	if o != nil && IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]string and assigns it to the CustomFields field.
func (o *RequestAgainClientModel) SetCustomFields(v map[string]string) {
	o.CustomFields = v
}

// GetRunPreApprovalValidations returns the RunPreApprovalValidations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RequestAgainClientModel) GetRunPreApprovalValidations() bool {
	if o == nil || IsNil(o.RunPreApprovalValidations.Get()) {
		var ret bool
		return ret
	}
	return *o.RunPreApprovalValidations.Get()
}

// GetRunPreApprovalValidationsOk returns a tuple with the RunPreApprovalValidations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequestAgainClientModel) GetRunPreApprovalValidationsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunPreApprovalValidations.Get(), o.RunPreApprovalValidations.IsSet()
}

// HasRunPreApprovalValidations returns a boolean if a field has been set.
func (o *RequestAgainClientModel) HasRunPreApprovalValidations() bool {
	if o != nil && o.RunPreApprovalValidations.IsSet() {
		return true
	}

	return false
}

// SetRunPreApprovalValidations gets a reference to the given NullableBool and assigns it to the RunPreApprovalValidations field.
func (o *RequestAgainClientModel) SetRunPreApprovalValidations(v bool) {
	o.RunPreApprovalValidations.Set(&v)
}

// SetRunPreApprovalValidationsNil sets the value for RunPreApprovalValidations to be an explicit nil
func (o *RequestAgainClientModel) SetRunPreApprovalValidationsNil() {
	o.RunPreApprovalValidations.Set(nil)
}

// UnsetRunPreApprovalValidations ensures that no value is present for RunPreApprovalValidations, not even an explicit nil
func (o *RequestAgainClientModel) UnsetRunPreApprovalValidations() {
	o.RunPreApprovalValidations.Unset()
}

func (o RequestAgainClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgainClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["justification"] = o.Justification
	if o.CustomFields != nil {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if o.RunPreApprovalValidations.IsSet() {
		toSerialize["run_pre_approval_validations"] = o.RunPreApprovalValidations.Get()
	}
	return toSerialize, nil
}

func (o *RequestAgainClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"justification",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgainClientModel := _RequestAgainClientModel{}

	err = json.Unmarshal(bytes, &varRequestAgainClientModel)

	if err != nil {
		return err
	}

	*o = RequestAgainClientModel(varRequestAgainClientModel)

	return err
}

type NullableRequestAgainClientModel struct {
	value *RequestAgainClientModel
	isSet bool
}

func (v NullableRequestAgainClientModel) Get() *RequestAgainClientModel {
	return v.value
}

func (v *NullableRequestAgainClientModel) Set(val *RequestAgainClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgainClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgainClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgainClientModel(val *RequestAgainClientModel) *NullableRequestAgainClientModel {
	return &NullableRequestAgainClientModel{value: val, isSet: true}
}

func (v NullableRequestAgainClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgainClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
