/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
)

// checks if the AssistantMessageDataClientModelClientRequestCta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantMessageDataClientModelClientRequestCta{}

// AssistantMessageDataClientModelClientRequestCta struct for AssistantMessageDataClientModelClientRequestCta
type AssistantMessageDataClientModelClientRequestCta struct {
	ResourcesRequest NullableMessageDataRequestCTAClientModelResourcesRequest `json:"resources_request,omitempty"`
	BundlesRequest   NullableMessageDataRequestCTAClientModelBundlesRequest   `json:"bundles_request,omitempty"`
	RequestAgain     NullableMessageDataRequestCTAClientModelRequestAgain     `json:"request_again,omitempty"`
}

// NewAssistantMessageDataClientModelClientRequestCta instantiates a new AssistantMessageDataClientModelClientRequestCta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantMessageDataClientModelClientRequestCta() *AssistantMessageDataClientModelClientRequestCta {
	this := AssistantMessageDataClientModelClientRequestCta{}
	return &this
}

// NewAssistantMessageDataClientModelClientRequestCtaWithDefaults instantiates a new AssistantMessageDataClientModelClientRequestCta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantMessageDataClientModelClientRequestCtaWithDefaults() *AssistantMessageDataClientModelClientRequestCta {
	this := AssistantMessageDataClientModelClientRequestCta{}
	return &this
}

// GetResourcesRequest returns the ResourcesRequest field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageDataClientModelClientRequestCta) GetResourcesRequest() MessageDataRequestCTAClientModelResourcesRequest {
	if o == nil || IsNil(o.ResourcesRequest.Get()) {
		var ret MessageDataRequestCTAClientModelResourcesRequest
		return ret
	}
	return *o.ResourcesRequest.Get()
}

// GetResourcesRequestOk returns a tuple with the ResourcesRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageDataClientModelClientRequestCta) GetResourcesRequestOk() (*MessageDataRequestCTAClientModelResourcesRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourcesRequest.Get(), o.ResourcesRequest.IsSet()
}

// HasResourcesRequest returns a boolean if a field has been set.
func (o *AssistantMessageDataClientModelClientRequestCta) HasResourcesRequest() bool {
	if o != nil && o.ResourcesRequest.IsSet() {
		return true
	}

	return false
}

// SetResourcesRequest gets a reference to the given NullableMessageDataRequestCTAClientModelResourcesRequest and assigns it to the ResourcesRequest field.
func (o *AssistantMessageDataClientModelClientRequestCta) SetResourcesRequest(v MessageDataRequestCTAClientModelResourcesRequest) {
	o.ResourcesRequest.Set(&v)
}

// SetResourcesRequestNil sets the value for ResourcesRequest to be an explicit nil
func (o *AssistantMessageDataClientModelClientRequestCta) SetResourcesRequestNil() {
	o.ResourcesRequest.Set(nil)
}

// UnsetResourcesRequest ensures that no value is present for ResourcesRequest, not even an explicit nil
func (o *AssistantMessageDataClientModelClientRequestCta) UnsetResourcesRequest() {
	o.ResourcesRequest.Unset()
}

// GetBundlesRequest returns the BundlesRequest field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageDataClientModelClientRequestCta) GetBundlesRequest() MessageDataRequestCTAClientModelBundlesRequest {
	if o == nil || IsNil(o.BundlesRequest.Get()) {
		var ret MessageDataRequestCTAClientModelBundlesRequest
		return ret
	}
	return *o.BundlesRequest.Get()
}

// GetBundlesRequestOk returns a tuple with the BundlesRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageDataClientModelClientRequestCta) GetBundlesRequestOk() (*MessageDataRequestCTAClientModelBundlesRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.BundlesRequest.Get(), o.BundlesRequest.IsSet()
}

// HasBundlesRequest returns a boolean if a field has been set.
func (o *AssistantMessageDataClientModelClientRequestCta) HasBundlesRequest() bool {
	if o != nil && o.BundlesRequest.IsSet() {
		return true
	}

	return false
}

// SetBundlesRequest gets a reference to the given NullableMessageDataRequestCTAClientModelBundlesRequest and assigns it to the BundlesRequest field.
func (o *AssistantMessageDataClientModelClientRequestCta) SetBundlesRequest(v MessageDataRequestCTAClientModelBundlesRequest) {
	o.BundlesRequest.Set(&v)
}

// SetBundlesRequestNil sets the value for BundlesRequest to be an explicit nil
func (o *AssistantMessageDataClientModelClientRequestCta) SetBundlesRequestNil() {
	o.BundlesRequest.Set(nil)
}

// UnsetBundlesRequest ensures that no value is present for BundlesRequest, not even an explicit nil
func (o *AssistantMessageDataClientModelClientRequestCta) UnsetBundlesRequest() {
	o.BundlesRequest.Unset()
}

// GetRequestAgain returns the RequestAgain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageDataClientModelClientRequestCta) GetRequestAgain() MessageDataRequestCTAClientModelRequestAgain {
	if o == nil || IsNil(o.RequestAgain.Get()) {
		var ret MessageDataRequestCTAClientModelRequestAgain
		return ret
	}
	return *o.RequestAgain.Get()
}

// GetRequestAgainOk returns a tuple with the RequestAgain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageDataClientModelClientRequestCta) GetRequestAgainOk() (*MessageDataRequestCTAClientModelRequestAgain, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestAgain.Get(), o.RequestAgain.IsSet()
}

// HasRequestAgain returns a boolean if a field has been set.
func (o *AssistantMessageDataClientModelClientRequestCta) HasRequestAgain() bool {
	if o != nil && o.RequestAgain.IsSet() {
		return true
	}

	return false
}

// SetRequestAgain gets a reference to the given NullableMessageDataRequestCTAClientModelRequestAgain and assigns it to the RequestAgain field.
func (o *AssistantMessageDataClientModelClientRequestCta) SetRequestAgain(v MessageDataRequestCTAClientModelRequestAgain) {
	o.RequestAgain.Set(&v)
}

// SetRequestAgainNil sets the value for RequestAgain to be an explicit nil
func (o *AssistantMessageDataClientModelClientRequestCta) SetRequestAgainNil() {
	o.RequestAgain.Set(nil)
}

// UnsetRequestAgain ensures that no value is present for RequestAgain, not even an explicit nil
func (o *AssistantMessageDataClientModelClientRequestCta) UnsetRequestAgain() {
	o.RequestAgain.Unset()
}

func (o AssistantMessageDataClientModelClientRequestCta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantMessageDataClientModelClientRequestCta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ResourcesRequest.IsSet() {
		toSerialize["resources_request"] = o.ResourcesRequest.Get()
	}
	if o.BundlesRequest.IsSet() {
		toSerialize["bundles_request"] = o.BundlesRequest.Get()
	}
	if o.RequestAgain.IsSet() {
		toSerialize["request_again"] = o.RequestAgain.Get()
	}
	return toSerialize, nil
}

type NullableAssistantMessageDataClientModelClientRequestCta struct {
	value *AssistantMessageDataClientModelClientRequestCta
	isSet bool
}

func (v NullableAssistantMessageDataClientModelClientRequestCta) Get() *AssistantMessageDataClientModelClientRequestCta {
	return v.value
}

func (v *NullableAssistantMessageDataClientModelClientRequestCta) Set(val *AssistantMessageDataClientModelClientRequestCta) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantMessageDataClientModelClientRequestCta) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantMessageDataClientModelClientRequestCta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantMessageDataClientModelClientRequestCta(val *AssistantMessageDataClientModelClientRequestCta) *NullableAssistantMessageDataClientModelClientRequestCta {
	return &NullableAssistantMessageDataClientModelClientRequestCta{value: val, isSet: true}
}

func (v NullableAssistantMessageDataClientModelClientRequestCta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantMessageDataClientModelClientRequestCta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
