/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MessageDataRequestResourcesClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageDataRequestResourcesClientModel{}

// MessageDataRequestResourcesClientModel struct for MessageDataRequestResourcesClientModel
type MessageDataRequestResourcesClientModel struct {
	Entitlements     []map[string]interface{} `json:"entitlements"`
	Justification    string                   `json:"justification"`
	RequiresApproval bool                     `json:"requires_approval"`
}

type _MessageDataRequestResourcesClientModel MessageDataRequestResourcesClientModel

// NewMessageDataRequestResourcesClientModel instantiates a new MessageDataRequestResourcesClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageDataRequestResourcesClientModel(entitlements []map[string]interface{}, justification string, requiresApproval bool) *MessageDataRequestResourcesClientModel {
	this := MessageDataRequestResourcesClientModel{}
	this.Entitlements = entitlements
	this.Justification = justification
	this.RequiresApproval = requiresApproval
	return &this
}

// NewMessageDataRequestResourcesClientModelWithDefaults instantiates a new MessageDataRequestResourcesClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageDataRequestResourcesClientModelWithDefaults() *MessageDataRequestResourcesClientModel {
	this := MessageDataRequestResourcesClientModel{}
	return &this
}

// GetEntitlements returns the Entitlements field value
func (o *MessageDataRequestResourcesClientModel) GetEntitlements() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Entitlements
}

// GetEntitlementsOk returns a tuple with the Entitlements field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestResourcesClientModel) GetEntitlementsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entitlements, true
}

// SetEntitlements sets field value
func (o *MessageDataRequestResourcesClientModel) SetEntitlements(v []map[string]interface{}) {
	o.Entitlements = v
}

// GetJustification returns the Justification field value
func (o *MessageDataRequestResourcesClientModel) GetJustification() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Justification
}

// GetJustificationOk returns a tuple with the Justification field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestResourcesClientModel) GetJustificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Justification, true
}

// SetJustification sets field value
func (o *MessageDataRequestResourcesClientModel) SetJustification(v string) {
	o.Justification = v
}

// GetRequiresApproval returns the RequiresApproval field value
func (o *MessageDataRequestResourcesClientModel) GetRequiresApproval() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresApproval
}

// GetRequiresApprovalOk returns a tuple with the RequiresApproval field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestResourcesClientModel) GetRequiresApprovalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresApproval, true
}

// SetRequiresApproval sets field value
func (o *MessageDataRequestResourcesClientModel) SetRequiresApproval(v bool) {
	o.RequiresApproval = v
}

func (o MessageDataRequestResourcesClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageDataRequestResourcesClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entitlements"] = o.Entitlements
	toSerialize["justification"] = o.Justification
	toSerialize["requires_approval"] = o.RequiresApproval
	return toSerialize, nil
}

func (o *MessageDataRequestResourcesClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entitlements",
		"justification",
		"requires_approval",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageDataRequestResourcesClientModel := _MessageDataRequestResourcesClientModel{}

	err = json.Unmarshal(bytes, &varMessageDataRequestResourcesClientModel)

	if err != nil {
		return err
	}

	*o = MessageDataRequestResourcesClientModel(varMessageDataRequestResourcesClientModel)

	return err
}

type NullableMessageDataRequestResourcesClientModel struct {
	value *MessageDataRequestResourcesClientModel
	isSet bool
}

func (v NullableMessageDataRequestResourcesClientModel) Get() *MessageDataRequestResourcesClientModel {
	return v.value
}

func (v *NullableMessageDataRequestResourcesClientModel) Set(val *MessageDataRequestResourcesClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageDataRequestResourcesClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageDataRequestResourcesClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageDataRequestResourcesClientModel(val *MessageDataRequestResourcesClientModel) *NullableMessageDataRequestResourcesClientModel {
	return &NullableMessageDataRequestResourcesClientModel{value: val, isSet: true}
}

func (v NullableMessageDataRequestResourcesClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageDataRequestResourcesClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
