/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateAnalyticEventsBatchClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAnalyticEventsBatchClientModel{}

// CreateAnalyticEventsBatchClientModel struct for CreateAnalyticEventsBatchClientModel
type CreateAnalyticEventsBatchClientModel struct {
	Events []CreateAnalyticEventClientModel `json:"events"`
}

type _CreateAnalyticEventsBatchClientModel CreateAnalyticEventsBatchClientModel

// NewCreateAnalyticEventsBatchClientModel instantiates a new CreateAnalyticEventsBatchClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAnalyticEventsBatchClientModel(events []CreateAnalyticEventClientModel) *CreateAnalyticEventsBatchClientModel {
	this := CreateAnalyticEventsBatchClientModel{}
	this.Events = events
	return &this
}

// NewCreateAnalyticEventsBatchClientModelWithDefaults instantiates a new CreateAnalyticEventsBatchClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAnalyticEventsBatchClientModelWithDefaults() *CreateAnalyticEventsBatchClientModel {
	this := CreateAnalyticEventsBatchClientModel{}
	return &this
}

// GetEvents returns the Events field value
func (o *CreateAnalyticEventsBatchClientModel) GetEvents() []CreateAnalyticEventClientModel {
	if o == nil {
		var ret []CreateAnalyticEventClientModel
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *CreateAnalyticEventsBatchClientModel) GetEventsOk() ([]CreateAnalyticEventClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *CreateAnalyticEventsBatchClientModel) SetEvents(v []CreateAnalyticEventClientModel) {
	o.Events = v
}

func (o CreateAnalyticEventsBatchClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAnalyticEventsBatchClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *CreateAnalyticEventsBatchClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAnalyticEventsBatchClientModel := _CreateAnalyticEventsBatchClientModel{}

	err = json.Unmarshal(bytes, &varCreateAnalyticEventsBatchClientModel)

	if err != nil {
		return err
	}

	*o = CreateAnalyticEventsBatchClientModel(varCreateAnalyticEventsBatchClientModel)

	return err
}

type NullableCreateAnalyticEventsBatchClientModel struct {
	value *CreateAnalyticEventsBatchClientModel
	isSet bool
}

func (v NullableCreateAnalyticEventsBatchClientModel) Get() *CreateAnalyticEventsBatchClientModel {
	return v.value
}

func (v *NullableCreateAnalyticEventsBatchClientModel) Set(val *CreateAnalyticEventsBatchClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAnalyticEventsBatchClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAnalyticEventsBatchClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAnalyticEventsBatchClientModel(val *CreateAnalyticEventsBatchClientModel) *NullableCreateAnalyticEventsBatchClientModel {
	return &NullableCreateAnalyticEventsBatchClientModel{value: val, isSet: true}
}

func (v NullableCreateAnalyticEventsBatchClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAnalyticEventsBatchClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
