/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AssistantMessageFeedbackModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantMessageFeedbackModel{}

// AssistantMessageFeedbackModel struct for AssistantMessageFeedbackModel
type AssistantMessageFeedbackModel struct {
	Feedback string `json:"feedback"`
}

type _AssistantMessageFeedbackModel AssistantMessageFeedbackModel

// NewAssistantMessageFeedbackModel instantiates a new AssistantMessageFeedbackModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantMessageFeedbackModel(feedback string) *AssistantMessageFeedbackModel {
	this := AssistantMessageFeedbackModel{}
	this.Feedback = feedback
	return &this
}

// NewAssistantMessageFeedbackModelWithDefaults instantiates a new AssistantMessageFeedbackModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantMessageFeedbackModelWithDefaults() *AssistantMessageFeedbackModel {
	this := AssistantMessageFeedbackModel{}
	return &this
}

// GetFeedback returns the Feedback field value
func (o *AssistantMessageFeedbackModel) GetFeedback() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Feedback
}

// GetFeedbackOk returns a tuple with the Feedback field value
// and a boolean to check if the value has been set.
func (o *AssistantMessageFeedbackModel) GetFeedbackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Feedback, true
}

// SetFeedback sets field value
func (o *AssistantMessageFeedbackModel) SetFeedback(v string) {
	o.Feedback = v
}

func (o AssistantMessageFeedbackModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantMessageFeedbackModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["feedback"] = o.Feedback
	return toSerialize, nil
}

func (o *AssistantMessageFeedbackModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"feedback",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssistantMessageFeedbackModel := _AssistantMessageFeedbackModel{}

	err = json.Unmarshal(bytes, &varAssistantMessageFeedbackModel)

	if err != nil {
		return err
	}

	*o = AssistantMessageFeedbackModel(varAssistantMessageFeedbackModel)

	return err
}

type NullableAssistantMessageFeedbackModel struct {
	value *AssistantMessageFeedbackModel
	isSet bool
}

func (v NullableAssistantMessageFeedbackModel) Get() *AssistantMessageFeedbackModel {
	return v.value
}

func (v *NullableAssistantMessageFeedbackModel) Set(val *AssistantMessageFeedbackModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantMessageFeedbackModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantMessageFeedbackModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantMessageFeedbackModel(val *AssistantMessageFeedbackModel) *NullableAssistantMessageFeedbackModel {
	return &NullableAssistantMessageFeedbackModel{value: val, isSet: true}
}

func (v NullableAssistantMessageFeedbackModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantMessageFeedbackModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
