/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResponseMcpServerClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseMcpServerClientModel{}

// PaginatedResponseMcpServerClientModel struct for PaginatedResponseMcpServerClientModel
type PaginatedResponseMcpServerClientModel struct {
	Data       []McpServerClientModel `json:"data"`
	Pagination PaginationInfo         `json:"pagination"`
}

type _PaginatedResponseMcpServerClientModel PaginatedResponseMcpServerClientModel

// NewPaginatedResponseMcpServerClientModel instantiates a new PaginatedResponseMcpServerClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseMcpServerClientModel(data []McpServerClientModel, pagination PaginationInfo) *PaginatedResponseMcpServerClientModel {
	this := PaginatedResponseMcpServerClientModel{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewPaginatedResponseMcpServerClientModelWithDefaults instantiates a new PaginatedResponseMcpServerClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseMcpServerClientModelWithDefaults() *PaginatedResponseMcpServerClientModel {
	this := PaginatedResponseMcpServerClientModel{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedResponseMcpServerClientModel) GetData() []McpServerClientModel {
	if o == nil {
		var ret []McpServerClientModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseMcpServerClientModel) GetDataOk() ([]McpServerClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedResponseMcpServerClientModel) SetData(v []McpServerClientModel) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *PaginatedResponseMcpServerClientModel) GetPagination() PaginationInfo {
	if o == nil {
		var ret PaginationInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseMcpServerClientModel) GetPaginationOk() (*PaginationInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedResponseMcpServerClientModel) SetPagination(v PaginationInfo) {
	o.Pagination = v
}

func (o PaginatedResponseMcpServerClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseMcpServerClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *PaginatedResponseMcpServerClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseMcpServerClientModel := _PaginatedResponseMcpServerClientModel{}

	err = json.Unmarshal(bytes, &varPaginatedResponseMcpServerClientModel)

	if err != nil {
		return err
	}

	*o = PaginatedResponseMcpServerClientModel(varPaginatedResponseMcpServerClientModel)

	return err
}

type NullablePaginatedResponseMcpServerClientModel struct {
	value *PaginatedResponseMcpServerClientModel
	isSet bool
}

func (v NullablePaginatedResponseMcpServerClientModel) Get() *PaginatedResponseMcpServerClientModel {
	return v.value
}

func (v *NullablePaginatedResponseMcpServerClientModel) Set(val *PaginatedResponseMcpServerClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseMcpServerClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseMcpServerClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseMcpServerClientModel(val *PaginatedResponseMcpServerClientModel) *NullablePaginatedResponseMcpServerClientModel {
	return &NullablePaginatedResponseMcpServerClientModel{value: val, isSet: true}
}

func (v NullablePaginatedResponseMcpServerClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseMcpServerClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
