/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SystemPromptClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemPromptClientModel{}

// SystemPromptClientModel struct for SystemPromptClientModel
type SystemPromptClientModel struct {
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Version     float64 `json:"version"`
	IsDefault   bool    `json:"is_default"`
}

type _SystemPromptClientModel SystemPromptClientModel

// NewSystemPromptClientModel instantiates a new SystemPromptClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemPromptClientModel(id string, name string, description string, version float64, isDefault bool) *SystemPromptClientModel {
	this := SystemPromptClientModel{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.Version = version
	this.IsDefault = isDefault
	return &this
}

// NewSystemPromptClientModelWithDefaults instantiates a new SystemPromptClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemPromptClientModelWithDefaults() *SystemPromptClientModel {
	this := SystemPromptClientModel{}
	return &this
}

// GetId returns the Id field value
func (o *SystemPromptClientModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SystemPromptClientModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SystemPromptClientModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SystemPromptClientModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SystemPromptClientModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SystemPromptClientModel) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SystemPromptClientModel) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SystemPromptClientModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SystemPromptClientModel) SetDescription(v string) {
	o.Description = v
}

// GetVersion returns the Version field value
func (o *SystemPromptClientModel) GetVersion() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *SystemPromptClientModel) GetVersionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *SystemPromptClientModel) SetVersion(v float64) {
	o.Version = v
}

// GetIsDefault returns the IsDefault field value
func (o *SystemPromptClientModel) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *SystemPromptClientModel) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *SystemPromptClientModel) SetIsDefault(v bool) {
	o.IsDefault = v
}

func (o SystemPromptClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemPromptClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["version"] = o.Version
	toSerialize["is_default"] = o.IsDefault
	return toSerialize, nil
}

func (o *SystemPromptClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"version",
		"is_default",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemPromptClientModel := _SystemPromptClientModel{}

	err = json.Unmarshal(bytes, &varSystemPromptClientModel)

	if err != nil {
		return err
	}

	*o = SystemPromptClientModel(varSystemPromptClientModel)

	return err
}

type NullableSystemPromptClientModel struct {
	value *SystemPromptClientModel
	isSet bool
}

func (v NullableSystemPromptClientModel) Get() *SystemPromptClientModel {
	return v.value
}

func (v *NullableSystemPromptClientModel) Set(val *SystemPromptClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemPromptClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemPromptClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemPromptClientModel(val *SystemPromptClientModel) *NullableSystemPromptClientModel {
	return &NullableSystemPromptClientModel{value: val, isSet: true}
}

func (v NullableSystemPromptClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemPromptClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
