/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MessageDataRequestCTAClientModelResourcesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageDataRequestCTAClientModelResourcesRequest{}

// MessageDataRequestCTAClientModelResourcesRequest struct for MessageDataRequestCTAClientModelResourcesRequest
type MessageDataRequestCTAClientModelResourcesRequest struct {
	Entitlements     []AccessUnitClientModel `json:"entitlements"`
	Justification    string                  `json:"justification"`
	RequiresApproval bool                    `json:"requires_approval"`
	ValidRequest     bool                    `json:"valid_request"`
}

type _MessageDataRequestCTAClientModelResourcesRequest MessageDataRequestCTAClientModelResourcesRequest

// NewMessageDataRequestCTAClientModelResourcesRequest instantiates a new MessageDataRequestCTAClientModelResourcesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageDataRequestCTAClientModelResourcesRequest(entitlements []AccessUnitClientModel, justification string, requiresApproval bool, validRequest bool) *MessageDataRequestCTAClientModelResourcesRequest {
	this := MessageDataRequestCTAClientModelResourcesRequest{}
	this.Entitlements = entitlements
	this.Justification = justification
	this.RequiresApproval = requiresApproval
	this.ValidRequest = validRequest
	return &this
}

// NewMessageDataRequestCTAClientModelResourcesRequestWithDefaults instantiates a new MessageDataRequestCTAClientModelResourcesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageDataRequestCTAClientModelResourcesRequestWithDefaults() *MessageDataRequestCTAClientModelResourcesRequest {
	this := MessageDataRequestCTAClientModelResourcesRequest{}
	return &this
}

// GetEntitlements returns the Entitlements field value
func (o *MessageDataRequestCTAClientModelResourcesRequest) GetEntitlements() []AccessUnitClientModel {
	if o == nil {
		var ret []AccessUnitClientModel
		return ret
	}

	return o.Entitlements
}

// GetEntitlementsOk returns a tuple with the Entitlements field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestCTAClientModelResourcesRequest) GetEntitlementsOk() ([]AccessUnitClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entitlements, true
}

// SetEntitlements sets field value
func (o *MessageDataRequestCTAClientModelResourcesRequest) SetEntitlements(v []AccessUnitClientModel) {
	o.Entitlements = v
}

// GetJustification returns the Justification field value
func (o *MessageDataRequestCTAClientModelResourcesRequest) GetJustification() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Justification
}

// GetJustificationOk returns a tuple with the Justification field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestCTAClientModelResourcesRequest) GetJustificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Justification, true
}

// SetJustification sets field value
func (o *MessageDataRequestCTAClientModelResourcesRequest) SetJustification(v string) {
	o.Justification = v
}

// GetRequiresApproval returns the RequiresApproval field value
func (o *MessageDataRequestCTAClientModelResourcesRequest) GetRequiresApproval() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresApproval
}

// GetRequiresApprovalOk returns a tuple with the RequiresApproval field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestCTAClientModelResourcesRequest) GetRequiresApprovalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresApproval, true
}

// SetRequiresApproval sets field value
func (o *MessageDataRequestCTAClientModelResourcesRequest) SetRequiresApproval(v bool) {
	o.RequiresApproval = v
}

// GetValidRequest returns the ValidRequest field value
func (o *MessageDataRequestCTAClientModelResourcesRequest) GetValidRequest() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ValidRequest
}

// GetValidRequestOk returns a tuple with the ValidRequest field value
// and a boolean to check if the value has been set.
func (o *MessageDataRequestCTAClientModelResourcesRequest) GetValidRequestOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidRequest, true
}

// SetValidRequest sets field value
func (o *MessageDataRequestCTAClientModelResourcesRequest) SetValidRequest(v bool) {
	o.ValidRequest = v
}

func (o MessageDataRequestCTAClientModelResourcesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageDataRequestCTAClientModelResourcesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entitlements"] = o.Entitlements
	toSerialize["justification"] = o.Justification
	toSerialize["requires_approval"] = o.RequiresApproval
	toSerialize["valid_request"] = o.ValidRequest
	return toSerialize, nil
}

func (o *MessageDataRequestCTAClientModelResourcesRequest) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entitlements",
		"justification",
		"requires_approval",
		"valid_request",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageDataRequestCTAClientModelResourcesRequest := _MessageDataRequestCTAClientModelResourcesRequest{}

	err = json.Unmarshal(bytes, &varMessageDataRequestCTAClientModelResourcesRequest)

	if err != nil {
		return err
	}

	*o = MessageDataRequestCTAClientModelResourcesRequest(varMessageDataRequestCTAClientModelResourcesRequest)

	return err
}

type NullableMessageDataRequestCTAClientModelResourcesRequest struct {
	value *MessageDataRequestCTAClientModelResourcesRequest
	isSet bool
}

func (v NullableMessageDataRequestCTAClientModelResourcesRequest) Get() *MessageDataRequestCTAClientModelResourcesRequest {
	return v.value
}

func (v *NullableMessageDataRequestCTAClientModelResourcesRequest) Set(val *MessageDataRequestCTAClientModelResourcesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageDataRequestCTAClientModelResourcesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageDataRequestCTAClientModelResourcesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageDataRequestCTAClientModelResourcesRequest(val *MessageDataRequestCTAClientModelResourcesRequest) *NullableMessageDataRequestCTAClientModelResourcesRequest {
	return &NullableMessageDataRequestCTAClientModelResourcesRequest{value: val, isSet: true}
}

func (v NullableMessageDataRequestCTAClientModelResourcesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageDataRequestCTAClientModelResourcesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
