/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
)

// checks if the AssistantMessageDataClientModelClientSearchCta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantMessageDataClientModelClientSearchCta{}

// AssistantMessageDataClientModelClientSearchCta struct for AssistantMessageDataClientModelClientSearchCta
type AssistantMessageDataClientModelClientSearchCta struct {
	Resources    NullableMessageDataSearchCTAClientModelResources    `json:"resources,omitempty"`
	Bundles      NullableMessageDataSearchCTAClientModelBundles      `json:"bundles,omitempty"`
	PastRequests NullableMessageDataSearchCTAClientModelPastRequests `json:"past_requests,omitempty"`
}

// NewAssistantMessageDataClientModelClientSearchCta instantiates a new AssistantMessageDataClientModelClientSearchCta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantMessageDataClientModelClientSearchCta() *AssistantMessageDataClientModelClientSearchCta {
	this := AssistantMessageDataClientModelClientSearchCta{}
	return &this
}

// NewAssistantMessageDataClientModelClientSearchCtaWithDefaults instantiates a new AssistantMessageDataClientModelClientSearchCta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantMessageDataClientModelClientSearchCtaWithDefaults() *AssistantMessageDataClientModelClientSearchCta {
	this := AssistantMessageDataClientModelClientSearchCta{}
	return &this
}

// GetResources returns the Resources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageDataClientModelClientSearchCta) GetResources() MessageDataSearchCTAClientModelResources {
	if o == nil || IsNil(o.Resources.Get()) {
		var ret MessageDataSearchCTAClientModelResources
		return ret
	}
	return *o.Resources.Get()
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageDataClientModelClientSearchCta) GetResourcesOk() (*MessageDataSearchCTAClientModelResources, bool) {
	if o == nil {
		return nil, false
	}
	return o.Resources.Get(), o.Resources.IsSet()
}

// HasResources returns a boolean if a field has been set.
func (o *AssistantMessageDataClientModelClientSearchCta) HasResources() bool {
	if o != nil && o.Resources.IsSet() {
		return true
	}

	return false
}

// SetResources gets a reference to the given NullableMessageDataSearchCTAClientModelResources and assigns it to the Resources field.
func (o *AssistantMessageDataClientModelClientSearchCta) SetResources(v MessageDataSearchCTAClientModelResources) {
	o.Resources.Set(&v)
}

// SetResourcesNil sets the value for Resources to be an explicit nil
func (o *AssistantMessageDataClientModelClientSearchCta) SetResourcesNil() {
	o.Resources.Set(nil)
}

// UnsetResources ensures that no value is present for Resources, not even an explicit nil
func (o *AssistantMessageDataClientModelClientSearchCta) UnsetResources() {
	o.Resources.Unset()
}

// GetBundles returns the Bundles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageDataClientModelClientSearchCta) GetBundles() MessageDataSearchCTAClientModelBundles {
	if o == nil || IsNil(o.Bundles.Get()) {
		var ret MessageDataSearchCTAClientModelBundles
		return ret
	}
	return *o.Bundles.Get()
}

// GetBundlesOk returns a tuple with the Bundles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageDataClientModelClientSearchCta) GetBundlesOk() (*MessageDataSearchCTAClientModelBundles, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bundles.Get(), o.Bundles.IsSet()
}

// HasBundles returns a boolean if a field has been set.
func (o *AssistantMessageDataClientModelClientSearchCta) HasBundles() bool {
	if o != nil && o.Bundles.IsSet() {
		return true
	}

	return false
}

// SetBundles gets a reference to the given NullableMessageDataSearchCTAClientModelBundles and assigns it to the Bundles field.
func (o *AssistantMessageDataClientModelClientSearchCta) SetBundles(v MessageDataSearchCTAClientModelBundles) {
	o.Bundles.Set(&v)
}

// SetBundlesNil sets the value for Bundles to be an explicit nil
func (o *AssistantMessageDataClientModelClientSearchCta) SetBundlesNil() {
	o.Bundles.Set(nil)
}

// UnsetBundles ensures that no value is present for Bundles, not even an explicit nil
func (o *AssistantMessageDataClientModelClientSearchCta) UnsetBundles() {
	o.Bundles.Unset()
}

// GetPastRequests returns the PastRequests field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantMessageDataClientModelClientSearchCta) GetPastRequests() MessageDataSearchCTAClientModelPastRequests {
	if o == nil || IsNil(o.PastRequests.Get()) {
		var ret MessageDataSearchCTAClientModelPastRequests
		return ret
	}
	return *o.PastRequests.Get()
}

// GetPastRequestsOk returns a tuple with the PastRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantMessageDataClientModelClientSearchCta) GetPastRequestsOk() (*MessageDataSearchCTAClientModelPastRequests, bool) {
	if o == nil {
		return nil, false
	}
	return o.PastRequests.Get(), o.PastRequests.IsSet()
}

// HasPastRequests returns a boolean if a field has been set.
func (o *AssistantMessageDataClientModelClientSearchCta) HasPastRequests() bool {
	if o != nil && o.PastRequests.IsSet() {
		return true
	}

	return false
}

// SetPastRequests gets a reference to the given NullableMessageDataSearchCTAClientModelPastRequests and assigns it to the PastRequests field.
func (o *AssistantMessageDataClientModelClientSearchCta) SetPastRequests(v MessageDataSearchCTAClientModelPastRequests) {
	o.PastRequests.Set(&v)
}

// SetPastRequestsNil sets the value for PastRequests to be an explicit nil
func (o *AssistantMessageDataClientModelClientSearchCta) SetPastRequestsNil() {
	o.PastRequests.Set(nil)
}

// UnsetPastRequests ensures that no value is present for PastRequests, not even an explicit nil
func (o *AssistantMessageDataClientModelClientSearchCta) UnsetPastRequests() {
	o.PastRequests.Unset()
}

func (o AssistantMessageDataClientModelClientSearchCta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantMessageDataClientModelClientSearchCta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Resources.IsSet() {
		toSerialize["resources"] = o.Resources.Get()
	}
	if o.Bundles.IsSet() {
		toSerialize["bundles"] = o.Bundles.Get()
	}
	if o.PastRequests.IsSet() {
		toSerialize["past_requests"] = o.PastRequests.Get()
	}
	return toSerialize, nil
}

type NullableAssistantMessageDataClientModelClientSearchCta struct {
	value *AssistantMessageDataClientModelClientSearchCta
	isSet bool
}

func (v NullableAssistantMessageDataClientModelClientSearchCta) Get() *AssistantMessageDataClientModelClientSearchCta {
	return v.value
}

func (v *NullableAssistantMessageDataClientModelClientSearchCta) Set(val *AssistantMessageDataClientModelClientSearchCta) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantMessageDataClientModelClientSearchCta) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantMessageDataClientModelClientSearchCta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantMessageDataClientModelClientSearchCta(val *AssistantMessageDataClientModelClientSearchCta) *NullableAssistantMessageDataClientModelClientSearchCta {
	return &NullableAssistantMessageDataClientModelClientSearchCta{value: val, isSet: true}
}

func (v NullableAssistantMessageDataClientModelClientSearchCta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantMessageDataClientModelClientSearchCta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
