/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the StdioServerConfigAppModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StdioServerConfigAppModel{}

// StdioServerConfigAppModel struct for StdioServerConfigAppModel
type StdioServerConfigAppModel struct {
	Command string            `json:"command"`
	Args    []string          `json:"args"`
	Env     map[string]string `json:"env"`
}

type _StdioServerConfigAppModel StdioServerConfigAppModel

// NewStdioServerConfigAppModel instantiates a new StdioServerConfigAppModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStdioServerConfigAppModel(command string, args []string, env map[string]string) *StdioServerConfigAppModel {
	this := StdioServerConfigAppModel{}
	this.Command = command
	this.Args = args
	this.Env = env
	return &this
}

// NewStdioServerConfigAppModelWithDefaults instantiates a new StdioServerConfigAppModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStdioServerConfigAppModelWithDefaults() *StdioServerConfigAppModel {
	this := StdioServerConfigAppModel{}
	return &this
}

// GetCommand returns the Command field value
func (o *StdioServerConfigAppModel) GetCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *StdioServerConfigAppModel) GetCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Command, true
}

// SetCommand sets field value
func (o *StdioServerConfigAppModel) SetCommand(v string) {
	o.Command = v
}

// GetArgs returns the Args field value
func (o *StdioServerConfigAppModel) GetArgs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *StdioServerConfigAppModel) GetArgsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Args, true
}

// SetArgs sets field value
func (o *StdioServerConfigAppModel) SetArgs(v []string) {
	o.Args = v
}

// GetEnv returns the Env field value
func (o *StdioServerConfigAppModel) GetEnv() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
func (o *StdioServerConfigAppModel) GetEnvOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Env, true
}

// SetEnv sets field value
func (o *StdioServerConfigAppModel) SetEnv(v map[string]string) {
	o.Env = v
}

func (o StdioServerConfigAppModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StdioServerConfigAppModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["command"] = o.Command
	toSerialize["args"] = o.Args
	toSerialize["env"] = o.Env
	return toSerialize, nil
}

func (o *StdioServerConfigAppModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"command",
		"args",
		"env",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStdioServerConfigAppModel := _StdioServerConfigAppModel{}

	err = json.Unmarshal(bytes, &varStdioServerConfigAppModel)

	if err != nil {
		return err
	}

	*o = StdioServerConfigAppModel(varStdioServerConfigAppModel)

	return err
}

type NullableStdioServerConfigAppModel struct {
	value *StdioServerConfigAppModel
	isSet bool
}

func (v NullableStdioServerConfigAppModel) Get() *StdioServerConfigAppModel {
	return v.value
}

func (v *NullableStdioServerConfigAppModel) Set(val *StdioServerConfigAppModel) {
	v.value = val
	v.isSet = true
}

func (v NullableStdioServerConfigAppModel) IsSet() bool {
	return v.isSet
}

func (v *NullableStdioServerConfigAppModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStdioServerConfigAppModel(val *StdioServerConfigAppModel) *NullableStdioServerConfigAppModel {
	return &NullableStdioServerConfigAppModel{value: val, isSet: true}
}

func (v NullableStdioServerConfigAppModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStdioServerConfigAppModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
