/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CliMessagesClientListModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CliMessagesClientListModel{}

// CliMessagesClientListModel struct for CliMessagesClientListModel
type CliMessagesClientListModel struct {
	Messages []CliMessageClientModel `json:"messages"`
}

type _CliMessagesClientListModel CliMessagesClientListModel

// NewCliMessagesClientListModel instantiates a new CliMessagesClientListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCliMessagesClientListModel(messages []CliMessageClientModel) *CliMessagesClientListModel {
	this := CliMessagesClientListModel{}
	this.Messages = messages
	return &this
}

// NewCliMessagesClientListModelWithDefaults instantiates a new CliMessagesClientListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCliMessagesClientListModelWithDefaults() *CliMessagesClientListModel {
	this := CliMessagesClientListModel{}
	return &this
}

// GetMessages returns the Messages field value
func (o *CliMessagesClientListModel) GetMessages() []CliMessageClientModel {
	if o == nil {
		var ret []CliMessageClientModel
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *CliMessagesClientListModel) GetMessagesOk() ([]CliMessageClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *CliMessagesClientListModel) SetMessages(v []CliMessageClientModel) {
	o.Messages = v
}

func (o CliMessagesClientListModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CliMessagesClientListModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messages"] = o.Messages
	return toSerialize, nil
}

func (o *CliMessagesClientListModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCliMessagesClientListModel := _CliMessagesClientListModel{}

	err = json.Unmarshal(bytes, &varCliMessagesClientListModel)

	if err != nil {
		return err
	}

	*o = CliMessagesClientListModel(varCliMessagesClientListModel)

	return err
}

type NullableCliMessagesClientListModel struct {
	value *CliMessagesClientListModel
	isSet bool
}

func (v NullableCliMessagesClientListModel) Get() *CliMessagesClientListModel {
	return v.value
}

func (v *NullableCliMessagesClientListModel) Set(val *CliMessagesClientListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCliMessagesClientListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCliMessagesClientListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCliMessagesClientListModel(val *CliMessagesClientListModel) *NullableCliMessagesClientListModel {
	return &NullableCliMessagesClientListModel{value: val, isSet: true}
}

func (v NullableCliMessagesClientListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCliMessagesClientListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
