name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{ secrets.APONO_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.APONO_GPG_PASSPHRASE }}

      - run: make inst

      - run: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          SCOOP_TAP_GITHUB_TOKEN: ${{ secrets.SCOOP_TAP_GITHUB_TOKEN }}

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
